import { Scenario, Category } from './types';

export const EMOJI_OPTIONS = ['😊', '🦊', '🐯', '🌸', '🎨', '🎵', '⚡', '🌈', '🍀', '🦋', '🌺', '🎭'];

export const PROFILE_GRADIENTS = [
  'linear-gradient(135deg, hsl(5 78% 57%), hsl(25 90% 60%))',
  'linear-gradient(135deg, hsl(37 90% 55%), hsl(45 95% 65%))',
  'linear-gradient(135deg, hsl(145 63% 42%), hsl(170 60% 50%))',
  'linear-gradient(135deg, hsl(210 80% 55%), hsl(230 70% 60%))',
  'linear-gradient(135deg, hsl(280 60% 55%), hsl(310 70% 60%))',
];

export const CATEGORIES: { name: Category; emoji: string }[] = [
  { name: 'Mua sắm', emoji: '🛒' },
  { name: 'Ẩm thực', emoji: '🍽️' },
  { name: 'Gia đình', emoji: '🏠' },
  { name: 'Di chuyển', emoji: '🚗' },
  { name: 'Công việc', emoji: '💼' },
  { name: 'Sức khỏe', emoji: '🏥' },
  { name: 'Xã hội', emoji: '🎉' },
  { name: 'Công nghệ', emoji: '📱' },
];

export const SCENARIOS: Scenario[] = [
  // ═══════════════════════════════════════════
  // 🛒 MUA SẮM (Shopping)
  // ═══════════════════════════════════════════
  {
    id: 'supermarket',
    category: 'Mua sắm', categoryEmoji: '🛒',
    title: 'Đi siêu thị',
    difficulty: 'Dễ', xp: 40,
    culturalTip: '🇪🇸 Ở TBN, siêu thị phổ biến nhất là Mercadona, Carrefour và Lidl. Nhiều siêu thị đóng cửa ngày Chủ nhật!',
    vocabulary: [
      { id: 'sh1', spanish: 'El supermercado', vietnamese: 'Siêu thị', phonetic: 'eo xu-pér-me-ca-đô', example: 'Voy al supermercado.', exampleVi: 'Tôi đi siêu thị.' },
      { id: 'sh2', spanish: 'La leche', vietnamese: 'Sữa', phonetic: 'la lê-chê', example: 'Necesito un litro de leche.', exampleVi: 'Tôi cần một lít sữa.' },
      { id: 'sh3', spanish: 'El pan', vietnamese: 'Bánh mì', phonetic: 'eo pan', example: 'El pan está fresco.', exampleVi: 'Bánh mì tươi.' },
      { id: 'sh4', spanish: 'La fruta', vietnamese: 'Trái cây', phonetic: 'la phrú-ta', example: '¿Dónde está la fruta?', exampleVi: 'Trái cây ở đâu?' },
      { id: 'sh5', spanish: 'La caja', vietnamese: 'Quầy thanh toán', phonetic: 'la ca-ha', example: 'Voy a la caja.', exampleVi: 'Tôi ra quầy thanh toán.' },
      { id: 'sh6', spanish: 'Una bolsa', vietnamese: 'Một túi', phonetic: 'u-na bol-xa', example: '¿Necesita una bolsa?', exampleVi: 'Bạn cần túi không?' },
      { id: 'sh7', spanish: 'El precio', vietnamese: 'Giá', phonetic: 'eo prê-xi-ô', example: '¿Cuál es el precio?', exampleVi: 'Giá bao nhiêu?' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn đang ở siêu thị Mercadona ở Madrid.', vietnamese: '' },
      { role: 'ai', spanish: '¡Buenos días! ¿Necesita ayuda para encontrar algo?', vietnamese: 'Chào buổi sáng! Bạn cần tìm gì không?', tip: '💡 "¿Necesita ayuda?" = Bạn cần giúp không? Rất phổ biến trong siêu thị.' },
      { role: 'user', spanish: 'Sí, ¿dónde está la leche?', vietnamese: 'Vâng, sữa ở đâu?' },
      { role: 'ai', spanish: 'La leche está en el pasillo tres, a la derecha.', vietnamese: 'Sữa ở lối đi số 3, bên phải.', tip: '💡 "pasillo" = lối đi. Trong siêu thị TBN, các lối đi được đánh số.' },
      { role: 'user', spanish: 'Gracias. ¿Y el pan?', vietnamese: 'Cảm ơn. Còn bánh mì?' },
      { role: 'ai', spanish: 'El pan fresco está al fondo, en la panadería. ¿Algo más?', vietnamese: 'Bánh mì tươi ở phía cuối, quầy bánh. Còn gì nữa không?', suggestions: ['No, gracias. ¿Dónde está la caja?', '¿Tienen fruta fresca?', '¿Cuánto cuesta el pan?'] },
    ],
  },
  {
    id: 'bakery',
    category: 'Mua sắm', categoryEmoji: '🛒',
    title: 'Mua bánh mì / bánh ngọt',
    difficulty: 'Dễ', xp: 35,
    culturalTip: '🇪🇸 Churros con chocolate là bữa sáng phổ biến ở TBN! Người TBN thường ăn sáng nhẹ, bữa trưa mới là bữa chính.',
    vocabulary: [
      { id: 'bk1', spanish: 'La panadería', vietnamese: 'Tiệm bánh mì', phonetic: 'la pa-na-đê-ri-a', example: 'Voy a la panadería.', exampleVi: 'Tôi đi tiệm bánh mì.' },
      { id: 'bk2', spanish: 'Un croissant', vietnamese: 'Bánh sừng bò', phonetic: 'un croa-xan', example: 'Quiero un croissant, por favor.', exampleVi: 'Tôi muốn một bánh sừng bò.' },
      { id: 'bk3', spanish: 'La tarta', vietnamese: 'Bánh kem', phonetic: 'la tar-ta', example: 'Una tarta de chocolate.', exampleVi: 'Một bánh kem sô-cô-la.' },
      { id: 'bk4', spanish: 'Los churros', vietnamese: 'Churros (bánh quẩy TBN)', phonetic: 'lốt chu-rrốt', example: 'Churros con chocolate, por favor.', exampleVi: 'Churros với sô-cô-la, làm ơn.' },
      { id: 'bk5', spanish: 'Recién hecho', vietnamese: 'Mới làm', phonetic: 'rê-xi-ên ê-chô', example: 'El pan está recién hecho.', exampleVi: 'Bánh mì mới làm.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn vào tiệm bánh mì ở khu phố.', vietnamese: '' },
      { role: 'ai', spanish: '¡Buenos días! ¿Qué le pongo?', vietnamese: 'Chào buổi sáng! Bạn muốn gì?', tip: '💡 "¿Qué le pongo?" là cách nói phổ biến trong tiệm, nghĩa là "Bạn muốn mua gì?"' },
      { role: 'user', spanish: 'Buenos días. Quiero dos barras de pan.', vietnamese: 'Chào. Tôi muốn hai ổ bánh mì.' },
      { role: 'ai', spanish: '¿Algo más? Hoy tenemos churros recién hechos.', vietnamese: 'Gì nữa không? Hôm nay có churros mới làm.', suggestions: ['Sí, ponme seis churros.', 'No, gracias. ¿Cuánto es?', '¿Tienen tarta de chocolate?'] },
    ],
  },
  {
    id: 'clothes-shopping',
    category: 'Mua sắm', categoryEmoji: '🛒',
    title: 'Mua quần áo',
    difficulty: 'Trung bình', xp: 50,
    culturalTip: '🇪🇸 Zara, Mango, và Massimo Dutti đều là thương hiệu TBN! "Rebajas" (giảm giá) thường vào tháng 1 và tháng 7.',
    vocabulary: [
      { id: 'cl1', spanish: 'La talla', vietnamese: 'Size / Cỡ', phonetic: 'la ta-gia', example: '¿Qué talla usa?', exampleVi: 'Bạn mặc size gì?' },
      { id: 'cl2', spanish: 'Probarse', vietnamese: 'Thử (quần áo)', phonetic: 'prô-bar-xê', example: '¿Puedo probarme esto?', exampleVi: 'Tôi thử cái này được không?' },
      { id: 'cl3', spanish: 'El probador', vietnamese: 'Phòng thử đồ', phonetic: 'eo prô-ba-đor', example: '¿Dónde está el probador?', exampleVi: 'Phòng thử đồ ở đâu?' },
      { id: 'cl4', spanish: 'Me queda bien', vietnamese: 'Vừa vặn', phonetic: 'mê kê-đa bi-en', example: 'Esta camisa me queda bien.', exampleVi: 'Áo sơ mi này vừa vặn.' },
      { id: 'cl5', spanish: 'Las rebajas', vietnamese: 'Đợt giảm giá', phonetic: 'lát rê-ba-hát', example: '¿Hay rebajas?', exampleVi: 'Có giảm giá không?' },
      { id: 'cl6', spanish: 'Devolver', vietnamese: 'Trả lại', phonetic: 'đê-bol-bér', example: '¿Puedo devolver esto?', exampleVi: 'Tôi trả lại cái này được không?' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn đang mua sắm ở cửa hàng Zara.', vietnamese: '' },
      { role: 'ai', spanish: '¡Hola! ¿Puedo ayudarle en algo?', vietnamese: 'Xin chào! Tôi giúp gì được?', tip: '💡 Nhân viên bán hàng thường dùng "usted" (lịch sự) với khách.' },
      { role: 'user', spanish: 'Sí, busco una camisa blanca.', vietnamese: 'Vâng, tôi tìm áo sơ mi trắng.' },
      { role: 'ai', spanish: '¿Qué talla usa? Tenemos S, M, L y XL.', vietnamese: 'Bạn mặc size gì? Có S, M, L và XL.', tip: '💡 "¿Qué talla usa?" = Size gì? Sizes ở TBN giống sizes châu Âu.' },
      { role: 'user', spanish: 'Talla M, por favor. ¿Puedo probarme esta?', vietnamese: 'Size M, làm ơn. Tôi thử cái này được không?' },
      { role: 'ai', spanish: 'Claro, el probador está al fondo a la izquierda.', vietnamese: 'Tất nhiên, phòng thử ở phía cuối bên trái.', suggestions: ['Me queda bien. Me la llevo.', '¿Tienen en otro color?', 'Me queda grande. ¿Tienen en S?'] },
    ],
  },
  {
    id: 'pharmacy-shopping',
    category: 'Mua sắm', categoryEmoji: '🛒',
    title: 'Mua thuốc ở hiệu thuốc',
    difficulty: 'Trung bình', xp: 50,
    culturalTip: '🇪🇸 Hiệu thuốc TBN có biểu tượng chữ thập xanh nhấp nháy. Có "farmacia de guardia" mở 24/7 theo lịch luân phiên.',
    vocabulary: [
      { id: 'ph1', spanish: 'La farmacia', vietnamese: 'Hiệu thuốc', phonetic: 'la phar-ma-xi-a', example: 'Necesito ir a la farmacia.', exampleVi: 'Tôi cần đi hiệu thuốc.' },
      { id: 'ph2', spanish: 'La receta', vietnamese: 'Đơn thuốc', phonetic: 'la rê-xê-ta', example: '¿Necesito receta?', exampleVi: 'Tôi cần đơn thuốc không?' },
      { id: 'ph3', spanish: 'Las pastillas', vietnamese: 'Viên thuốc', phonetic: 'lát pat-ti-giát', example: 'Necesito pastillas para el dolor.', exampleVi: 'Tôi cần thuốc giảm đau.' },
      { id: 'ph4', spanish: 'La crema solar', vietnamese: 'Kem chống nắng', phonetic: 'la crê-ma xô-la', example: '¿Tienen crema solar?', exampleVi: 'Có kem chống nắng không?' },
      { id: 'ph5', spanish: 'Sin receta', vietnamese: 'Không cần đơn', phonetic: 'xin rê-xê-ta', example: 'Esto es sin receta.', exampleVi: 'Cái này không cần đơn.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn bị cảm và cần mua thuốc.', vietnamese: '' },
      { role: 'ai', spanish: '¡Buenas tardes! ¿En qué puedo ayudarle?', vietnamese: 'Chào buổi chiều! Tôi giúp gì được?', tip: '💡 "¿En qué puedo ayudarle?" = Rất lịch sự, phổ biến trong dịch vụ.' },
      { role: 'user', spanish: 'Tengo tos y dolor de cabeza.', vietnamese: 'Tôi bị ho và đau đầu.' },
      { role: 'ai', spanish: 'Le recomiendo estas pastillas. Tome una cada ocho horas.', vietnamese: 'Tôi khuyên bạn dùng viên thuốc này. Uống 1 viên mỗi 8 giờ.', suggestions: ['¿Cuánto cuesta?', '¿Necesito receta?', '¿Tiene algo para la fiebre también?'] },
    ],
  },
  {
    id: 'market',
    category: 'Mua sắm', categoryEmoji: '🛒',
    title: 'Mua đồ ở chợ',
    difficulty: 'Khó', xp: 60,
    culturalTip: '🇪🇸 "Mercado" (chợ) ở TBN rất đẹp! Mercado de San Miguel ở Madrid là chợ nổi tiếng nhất, bán tapas và hải sản tươi.',
    vocabulary: [
      { id: 'mk1', spanish: 'El mercado', vietnamese: 'Chợ', phonetic: 'eo mer-ca-đô', example: 'Voy al mercado los sábados.', exampleVi: 'Tôi đi chợ thứ Bảy.' },
      { id: 'mk2', spanish: 'Un kilo de', vietnamese: 'Một ký', phonetic: 'un ki-lô đê', example: 'Un kilo de tomates, por favor.', exampleVi: 'Một ký cà chua, làm ơn.' },
      { id: 'mk3', spanish: 'Fresco/a', vietnamese: 'Tươi', phonetic: 'phrét-cô', example: '¿Está fresco?', exampleVi: 'Tươi không?' },
      { id: 'mk4', spanish: '¿A cuánto está?', vietnamese: 'Giá bao nhiêu?', phonetic: 'a coan-tô ét-ta', example: '¿A cuánto está el pescado?', exampleVi: 'Cá giá bao nhiêu?' },
      { id: 'mk5', spanish: 'Poner', vietnamese: 'Cho (bỏ vào)', phonetic: 'pô-nér', example: 'Póngame medio kilo.', exampleVi: 'Cho tôi nửa ký.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn đang mua hải sản ở chợ Mercado de la Boquería.', vietnamese: '' },
      { role: 'ai', spanish: '¡Buenos días! ¡Mire qué gambas tan frescas! ¿Le pongo?', vietnamese: 'Chào! Nhìn tôm tươi thế này! Bạn lấy không?', tip: '💡 Người bán ở chợ rất nhiệt tình, hay giới thiệu đồ tươi ngon.' },
      { role: 'user', spanish: 'Sí, póngame medio kilo de gambas.', vietnamese: 'Vâng, cho tôi nửa ký tôm.' },
      { role: 'ai', spanish: 'Aquí tiene. ¿Algo más? Hoy el salmón está muy bueno.', vietnamese: 'Đây ạ. Gì nữa không? Hôm nay cá hồi rất ngon.', suggestions: ['¿A cuánto está el salmón?', 'No, gracias. ¿Cuánto es todo?', 'Póngame un kilo de mejillones también.'] },
    ],
  },

  // ═══════════════════════════════════════════
  // 🍽️ ẨM THỰC (Food)
  // ═══════════════════════════════════════════
  {
    id: 'order-coffee',
    category: 'Ẩm thực', categoryEmoji: '🍽️',
    title: 'Gọi cà phê',
    difficulty: 'Dễ', xp: 35,
    culturalTip: '🇪🇸 Ở TBN, "café solo" = espresso đen, "café con leche" = cà phê sữa, "cortado" = espresso + ít sữa. Không có cà phê size lớn như ở Mỹ!',
    vocabulary: [
      { id: 'cf1', spanish: 'Un café solo', vietnamese: 'Cà phê đen', phonetic: 'un ca-phê xô-lô', example: 'Un café solo, por favor.', exampleVi: 'Một cà phê đen, làm ơn.' },
      { id: 'cf2', spanish: 'Un café con leche', vietnamese: 'Cà phê sữa', phonetic: 'un ca-phê con lê-chê', example: 'Quiero un café con leche.', exampleVi: 'Tôi muốn cà phê sữa.' },
      { id: 'cf3', spanish: 'Un cortado', vietnamese: 'Cortado (espresso + ít sữa)', phonetic: 'un cor-ta-đô', example: 'Para mí, un cortado.', exampleVi: 'Cho tôi một cortado.' },
      { id: 'cf4', spanish: 'Con hielo', vietnamese: 'Với đá', phonetic: 'con i-ê-lô', example: 'Un café con hielo, por favor.', exampleVi: 'Cà phê đá, làm ơn.' },
      { id: 'cf5', spanish: 'La tostada', vietnamese: 'Bánh mì nướng', phonetic: 'la tốt-ta-đa', example: 'Una tostada con tomate.', exampleVi: 'Bánh mì nướng với cà chua.' },
      { id: 'cf6', spanish: 'Para tomar aquí', vietnamese: 'Uống tại đây', phonetic: 'pa-ra tô-mar a-ki', example: 'Para tomar aquí, por favor.', exampleVi: 'Uống tại đây, làm ơn.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn vào một quán cà phê nhỏ ở Madrid buổi sáng.', vietnamese: '' },
      { role: 'ai', spanish: '¡Buenos días! ¿Qué le pongo?', vietnamese: 'Chào buổi sáng! Bạn muốn gì?', tip: '💡 "¿Qué le pongo?" là cách nói rất TBN, nghĩa là "Bạn dùng gì?"' },
      { role: 'user', spanish: 'Un café con leche, por favor.', vietnamese: 'Một cà phê sữa, làm ơn.' },
      { role: 'ai', spanish: '¿Grande o normal? ¿Con azúcar?', vietnamese: 'Lớn hay thường? Có đường không?', tip: '💡 "azúcar" = đường. Ở TBN thường để bạn tự thêm đường.' },
      { role: 'user', spanish: 'Normal, sin azúcar. Para tomar aquí.', vietnamese: 'Thường, không đường. Uống tại đây.' },
      { role: 'ai', spanish: 'Muy bien. ¿Quiere algo para comer? Tenemos tostadas y croissants.', vietnamese: 'Được. Bạn muốn ăn gì không? Có bánh mì nướng và croissant.', suggestions: ['Sí, una tostada con tomate.', 'No, gracias. Solo el café.', '¿Cuánto es todo?'] },
    ],
  },
  {
    id: 'spanish-restaurant',
    category: 'Ẩm thực', categoryEmoji: '🍽️',
    title: 'Nhà hàng Tây Ban Nha',
    difficulty: 'Trung bình', xp: 55,
    culturalTip: '🇪🇸 Người TBN ăn tối rất muộn (21-22h). "Menú del día" (thực đơn ngày) là combo giá rẻ gồm 2 món + nước + tráng miệng.',
    vocabulary: [
      { id: 'rs1', spanish: 'La carta / El menú', vietnamese: 'Thực đơn', phonetic: 'la các-ta', example: '¿Puedo ver la carta?', exampleVi: 'Cho tôi xem thực đơn?' },
      { id: 'rs2', spanish: 'Menú del día', vietnamese: 'Thực đơn ngày (combo)', phonetic: 'mê-nú đel đi-a', example: '¿Tienen menú del día?', exampleVi: 'Có thực đơn ngày không?' },
      { id: 'rs3', spanish: 'La paella', vietnamese: 'Cơm TBN (paella)', phonetic: 'la pa-ê-gia', example: 'La paella es para dos personas.', exampleVi: 'Paella cho hai người.' },
      { id: 'rs4', spanish: 'Las tapas', vietnamese: 'Tapas (đĩa nhỏ)', phonetic: 'lát ta-pát', example: 'Queremos unas tapas variadas.', exampleVi: 'Chúng tôi muốn tapas thập cẩm.' },
      { id: 'rs5', spanish: 'La cuenta', vietnamese: 'Hóa đơn', phonetic: 'la cuen-ta', example: 'La cuenta, por favor.', exampleVi: 'Tính tiền, làm ơn.' },
      { id: 'rs6', spanish: 'Reservar', vietnamese: 'Đặt bàn', phonetic: 'rê-xer-bar', example: 'Quiero reservar para esta noche.', exampleVi: 'Tôi muốn đặt bàn tối nay.' },
      { id: 'rs7', spanish: 'De primero/segundo', vietnamese: 'Món khai vị/chính', phonetic: 'đê pri-mê-rô', example: 'De primero, gazpacho.', exampleVi: 'Khai vị, súp lạnh gazpacho.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn đến nhà hàng tapas ở Sevilla.', vietnamese: '' },
      { role: 'ai', spanish: '¡Buenas noches! ¿Tienen reserva?', vietnamese: 'Chào buổi tối! Có đặt bàn chưa?', tip: '💡 "¿Tienen reserva?" = Có đặt bàn không? Nên đặt trước ở nhà hàng nổi tiếng.' },
      { role: 'user', spanish: 'No, ¿tienen mesa para dos?', vietnamese: 'Không, có bàn cho hai người không?' },
      { role: 'ai', spanish: 'Sí, por aquí. Aquí tiene la carta. ¿Quieren el menú del día?', vietnamese: 'Có, mời đi lối này. Đây là thực đơn. Muốn dùng menú del día không?', tip: '💡 "Menú del día" thường 10-15€, gồm 2 món + nước + tráng miệng. Rất hời!' },
      { role: 'user', spanish: 'Sí, ¿qué incluye el menú del día?', vietnamese: 'Vâng, menú del día gồm gì?' },
      { role: 'ai', spanish: 'De primero: gazpacho o ensalada. De segundo: paella o merluza. Postre incluido.', vietnamese: 'Khai vị: gazpacho hoặc salad. Chính: paella hoặc cá merluza. Kèm tráng miệng.', suggestions: ['De primero, gazpacho. De segundo, paella.', '¿Qué es el gazpacho?', '¿Tienen opciones vegetarianas?'] },
    ],
  },
  {
    id: 'cooking-together',
    category: 'Ẩm thực', categoryEmoji: '🍽️',
    title: 'Nấu ăn cùng nhau',
    difficulty: 'Trung bình', xp: 50,
    culturalTip: '🇪🇸 Tortilla española (trứng chiên khoai tây) là món quốc dân TBN. Mỗi gia đình đều có công thức riêng!',
    vocabulary: [
      { id: 'ck1', spanish: 'Cortar', vietnamese: 'Cắt', phonetic: 'cor-tar', example: 'Corta las cebollas.', exampleVi: 'Cắt hành.' },
      { id: 'ck2', spanish: 'Freír', vietnamese: 'Chiên', phonetic: 'phrê-ír', example: 'Fríe las patatas.', exampleVi: 'Chiên khoai tây.' },
      { id: 'ck3', spanish: 'Hervir', vietnamese: 'Luộc', phonetic: 'er-bír', example: 'Hierve el agua.', exampleVi: 'Đun nước sôi.' },
      { id: 'ck4', spanish: 'La sartén', vietnamese: 'Chảo', phonetic: 'la xar-tén', example: 'Pon aceite en la sartén.', exampleVi: 'Đổ dầu vào chảo.' },
      { id: 'ck5', spanish: 'La receta', vietnamese: 'Công thức', phonetic: 'la rê-xê-ta', example: '¿Tienes la receta?', exampleVi: 'Bạn có công thức không?' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn đang nấu tortilla española với bạn TBN.', vietnamese: '' },
      { role: 'ai', spanish: '¡Vamos a hacer una tortilla! Primero, pela las patatas.', vietnamese: 'Làm tortilla nào! Đầu tiên, gọt khoai tây.', tip: '💡 "Pelar" = gọt vỏ. Mệnh lệnh thân mật: pela, corta, fríe...' },
      { role: 'user', spanish: 'Vale. ¿Cuántas patatas necesitamos?', vietnamese: 'OK. Cần bao nhiêu khoai tây?' },
      { role: 'ai', spanish: 'Cuatro patatas grandes. Ahora, córtalas en láminas finas.', vietnamese: 'Bốn củ lớn. Giờ, cắt lát mỏng.', suggestions: ['¿Y los huevos?', '¿Con cebolla o sin cebolla?', '¿Cuánto aceite pongo?'] },
    ],
  },
  {
    id: 'food-delivery',
    category: 'Ẩm thực', categoryEmoji: '🍽️',
    title: 'Đặt đồ ăn giao hàng',
    difficulty: 'Dễ', xp: 40,
    culturalTip: '🇪🇸 Glovo và Just Eat là app giao đồ ăn phổ biến nhất ở TBN. Tiền boa không bắt buộc nhưng được đánh giá cao.',
    vocabulary: [
      { id: 'fd1', spanish: 'Pedir a domicilio', vietnamese: 'Đặt giao tận nhà', phonetic: 'pê-đir a đô-mi-xi-li-ô', example: 'Vamos a pedir a domicilio.', exampleVi: 'Mình đặt giao tận nhà đi.' },
      { id: 'fd2', spanish: 'La dirección', vietnamese: 'Địa chỉ', phonetic: 'la đi-rếc-xi-ôn', example: '¿Cuál es la dirección?', exampleVi: 'Địa chỉ là gì?' },
      { id: 'fd3', spanish: 'El repartidor', vietnamese: 'Người giao hàng', phonetic: 'eo rê-par-ti-đor', example: 'El repartidor llega en 30 minutos.', exampleVi: 'Người giao hàng đến trong 30 phút.' },
      { id: 'fd4', spanish: 'Pagar en efectivo', vietnamese: 'Trả tiền mặt', phonetic: 'pa-gar en ê-phếc-ti-bô', example: '¿Puedo pagar en efectivo?', exampleVi: 'Trả tiền mặt được không?' },
      { id: 'fd5', spanish: 'Con tarjeta', vietnamese: 'Bằng thẻ', phonetic: 'con tar-hê-ta', example: 'Pago con tarjeta.', exampleVi: 'Tôi trả bằng thẻ.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn gọi điện đặt pizza giao hàng.', vietnamese: '' },
      { role: 'ai', spanish: '¡Buenas noches! Pizzería España. ¿Qué desea?', vietnamese: 'Chào buổi tối! Tiệm Pizza España. Bạn muốn gì?', tip: '💡 Khi gọi điện, thường bắt đầu bằng "Buenas" + tên cửa hàng.' },
      { role: 'user', spanish: 'Quiero pedir una pizza margarita para llevar... digo, a domicilio.', vietnamese: 'Tôi muốn đặt pizza margarita mang đi... à, giao tận nhà.' },
      { role: 'ai', spanish: '¿Tamaño mediano o grande? ¿Quiere algo de beber?', vietnamese: 'Size vừa hay lớn? Có muốn đồ uống không?', suggestions: ['Grande, por favor. Y una Coca-Cola.', '¿Cuánto tarda el reparto?', '¿Cuál es la dirección?'] },
    ],
  },
  {
    id: 'describe-food',
    category: 'Ẩm thực', categoryEmoji: '🍽️',
    title: 'Mô tả món ăn',
    difficulty: 'Khó', xp: 60,
    culturalTip: '🇪🇸 "¡Está buenísimo!" là cách khen đồ ăn ngon nhất. Thêm "-ísimo" vào cuối tính từ để nhấn mạnh!',
    vocabulary: [
      { id: 'df1', spanish: 'Delicioso', vietnamese: 'Ngon tuyệt', phonetic: 'đê-li-xi-ô-xô', example: '¡Está delicioso!', exampleVi: 'Ngon tuyệt!' },
      { id: 'df2', spanish: 'Picante', vietnamese: 'Cay', phonetic: 'pi-can-tê', example: 'Es un poco picante.', exampleVi: 'Hơi cay.' },
      { id: 'df3', spanish: 'Dulce / Salado', vietnamese: 'Ngọt / Mặn', phonetic: 'đul-xê / xa-la-đô', example: 'Es dulce y salado a la vez.', exampleVi: 'Vừa ngọt vừa mặn.' },
      { id: 'df4', spanish: 'Crujiente', vietnamese: 'Giòn', phonetic: 'cru-hi-en-tê', example: 'Las patatas están crujientes.', exampleVi: 'Khoai tây giòn.' },
      { id: 'df5', spanish: 'Casero', vietnamese: 'Nhà làm', phonetic: 'ca-xê-rô', example: 'Es un plato casero.', exampleVi: 'Là món nhà làm.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn đang ăn tối với bạn TBN và muốn mô tả món ăn.', vietnamese: '' },
      { role: 'ai', spanish: '¿Qué te parece la paella? ¿Te gusta?', vietnamese: 'Bạn nghĩ sao về paella? Thích không?', tip: '💡 "¿Qué te parece?" = Bạn nghĩ sao? Dùng hỏi ý kiến.' },
      { role: 'user', spanish: '¡Está deliciosa! El arroz está perfecto.', vietnamese: 'Ngon tuyệt! Cơm hoàn hảo.' },
      { role: 'ai', spanish: '¿Quieres probar el gazpacho? Es una sopa fría con tomate, muy refrescante.', vietnamese: 'Bạn muốn thử gazpacho không? Là súp lạnh cà chua, rất mát.', suggestions: ['¡Sí! Me encanta probar cosas nuevas.', '¿Es picante?', '¿Cómo se hace?'] },
    ],
  },

  // ═══════════════════════════════════════════
  // 🏠 GIA ĐÌNH (Home)
  // ═══════════════════════════════════════════
  {
    id: 'morning-routine',
    category: 'Gia đình', categoryEmoji: '🏠',
    title: 'Thói quen buổi sáng',
    difficulty: 'Dễ', xp: 35,
    culturalTip: '🇪🇸 Người TBN thường ăn sáng rất nhẹ: café con leche + tostada. Bữa chính là trưa (14-15h)!',
    vocabulary: [
      { id: 'mr1', spanish: 'Despertarse', vietnamese: 'Thức dậy', phonetic: 'đét-per-tar-xê', example: 'Me despierto a las siete.', exampleVi: 'Tôi thức dậy lúc 7h.' },
      { id: 'mr2', spanish: 'Ducharse', vietnamese: 'Tắm', phonetic: 'đu-char-xê', example: 'Me ducho por la mañana.', exampleVi: 'Tôi tắm buổi sáng.' },
      { id: 'mr3', spanish: 'Desayunar', vietnamese: 'Ăn sáng', phonetic: 'đê-xa-iu-nar', example: 'Desayuno café con tostadas.', exampleVi: 'Tôi ăn sáng cà phê với bánh mì nướng.' },
      { id: 'mr4', spanish: 'Vestirse', vietnamese: 'Mặc quần áo', phonetic: 'bét-tir-xê', example: 'Los niños se visten solos.', exampleVi: 'Bọn trẻ tự mặc quần áo.' },
      { id: 'mr5', spanish: 'Salir de casa', vietnamese: 'Ra khỏi nhà', phonetic: 'xa-lir đê ca-xa', example: 'Salgo de casa a las ocho.', exampleVi: 'Tôi ra khỏi nhà lúc 8h.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn kể về thói quen buổi sáng với bạn TBN.', vietnamese: '' },
      { role: 'ai', spanish: '¿A qué hora te levantas normalmente?', vietnamese: 'Bình thường bạn dậy mấy giờ?', tip: '💡 "¿A qué hora...?" = Mấy giờ? Dùng cho mọi câu hỏi về thời gian.' },
      { role: 'user', spanish: 'Me levanto a las seis y media.', vietnamese: 'Tôi dậy lúc 6h30.' },
      { role: 'ai', spanish: '¡Qué temprano! ¿Qué haces primero?', vietnamese: 'Sớm quá! Bạn làm gì đầu tiên?', suggestions: ['Primero me ducho y después desayuno.', 'Primero hago ejercicio.', 'Primero preparo el desayuno para los niños.'] },
    ],
  },
  {
    id: 'help-kids-study',
    category: 'Gia đình', categoryEmoji: '🏠',
    title: 'Giúp con học bài',
    difficulty: 'Trung bình', xp: 50,
    culturalTip: '🇪🇸 Trẻ em TBN thường có "deberes" (bài tập về nhà) mỗi ngày. Trường học bắt đầu lúc 9h và kết thúc 14-17h.',
    vocabulary: [
      { id: 'ks1', spanish: 'Los deberes', vietnamese: 'Bài tập về nhà', phonetic: 'lốt đê-bê-rét', example: '¿Has terminado los deberes?', exampleVi: 'Con làm bài tập xong chưa?' },
      { id: 'ks2', spanish: 'Estudiar', vietnamese: 'Học', phonetic: 'ét-tu-đi-ar', example: 'Tienes que estudiar para el examen.', exampleVi: 'Con phải học cho bài thi.' },
      { id: 'ks3', spanish: 'El examen', vietnamese: 'Bài kiểm tra', phonetic: 'eo ếc-xa-men', example: 'Mañana tengo un examen.', exampleVi: 'Ngày mai con có kiểm tra.' },
      { id: 'ks4', spanish: 'Muy bien', vietnamese: 'Giỏi lắm', phonetic: 'muy bi-en', example: '¡Muy bien! ¡Excelente trabajo!', exampleVi: 'Giỏi lắm! Làm tốt lắm!' },
      { id: 'ks5', spanish: 'Necesitar ayuda', vietnamese: 'Cần giúp đỡ', phonetic: 'nê-xê-xi-tar a-iu-đa', example: '¿Necesitas ayuda con las matemáticas?', exampleVi: 'Con cần giúp môn toán không?' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn đang giúp con làm bài tập về nhà.', vietnamese: '' },
      { role: 'ai', spanish: 'Mamá, no entiendo este problema de matemáticas.', vietnamese: 'Mẹ ơi, con không hiểu bài toán này.', tip: '💡 "No entiendo" = Tôi không hiểu. Rất hữu ích khi học tiếng!' },
      { role: 'user', spanish: 'A ver, enséñame. ¿Cuál es el problema?', vietnamese: 'Để xem nào. Bài nào?' },
      { role: 'ai', spanish: 'Tengo que sumar estas fracciones, pero no sé cómo.', vietnamese: 'Con phải cộng phân số nhưng không biết cách.', suggestions: ['Primero, busca el mínimo común denominador.', '¿Tu profesor te ha explicado el método?', 'Vamos a hacerlo juntos paso a paso.'] },
    ],
  },
  {
    id: 'weekend-plans',
    category: 'Gia đình', categoryEmoji: '🏠',
    title: 'Kế hoạch cuối tuần',
    difficulty: 'Dễ', xp: 40,
    culturalTip: '🇪🇸 Cuối tuần, nhiều gia đình TBN đi "paseo" (dạo bộ) sau bữa trưa. Các quán bar/nhà hàng rất đông vào Chủ nhật trưa!',
    vocabulary: [
      { id: 'wp1', spanish: 'El fin de semana', vietnamese: 'Cuối tuần', phonetic: 'eo phin đê xê-ma-na', example: '¿Qué hacemos este fin de semana?', exampleVi: 'Cuối tuần này mình làm gì?' },
      { id: 'wp2', spanish: 'Ir al parque', vietnamese: 'Đi công viên', phonetic: 'ir ao par-kê', example: 'Vamos al parque con los niños.', exampleVi: 'Mình đi công viên với bọn trẻ.' },
      { id: 'wp3', spanish: 'Quedarse en casa', vietnamese: 'Ở nhà', phonetic: 'kê-đar-xê en ca-xa', example: 'Prefiero quedarme en casa.', exampleVi: 'Tôi thích ở nhà hơn.' },
      { id: 'wp4', spanish: 'Ir al cine', vietnamese: 'Đi xem phim', phonetic: 'ir ao xi-nê', example: '¿Vamos al cine el sábado?', exampleVi: 'Thứ bảy đi xem phim không?' },
      { id: 'wp5', spanish: 'Una excursión', vietnamese: 'Chuyến đi chơi', phonetic: 'u-na ếch-cur-xi-ôn', example: 'Podemos hacer una excursión a la montaña.', exampleVi: 'Mình có thể đi núi.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn đang bàn kế hoạch cuối tuần với gia đình.', vietnamese: '' },
      { role: 'ai', spanish: '¿Qué hacemos este fin de semana? Los niños quieren salir.', vietnamese: 'Cuối tuần làm gì? Bọn trẻ muốn đi chơi.', tip: '💡 "¿Qué hacemos?" = Mình làm gì? Dùng "nosotros" khi bàn kế hoạch nhóm.' },
      { role: 'user', spanish: 'Podemos ir al parque o al cine.', vietnamese: 'Mình có thể đi công viên hoặc xem phim.' },
      { role: 'ai', spanish: 'Si hace buen tiempo, mejor el parque. ¿Llevamos comida para un picnic?', vietnamese: 'Nếu thời tiết đẹp, công viên tốt hơn. Mang đồ ăn picnic nhé?', suggestions: ['¡Buena idea! Yo preparo los sándwiches.', 'Prefiero ir al cine, hace mucho calor.', '¿Y si vamos a la playa?'] },
    ],
  },
  {
    id: 'household-chores',
    category: 'Gia đình', categoryEmoji: '🏠',
    title: 'Việc nhà',
    difficulty: 'Dễ', xp: 35,
    culturalTip: '🇪🇸 Ở TBN, "fregar" (rửa bát) và "barrer" (quét nhà) là từ dùng hàng ngày. Máy rửa bát rất phổ biến.',
    vocabulary: [
      { id: 'ch1', spanish: 'Limpiar', vietnamese: 'Dọn dẹp', phonetic: 'lim-pi-ar', example: 'Hay que limpiar la casa.', exampleVi: 'Phải dọn nhà.' },
      { id: 'ch2', spanish: 'Cocinar', vietnamese: 'Nấu ăn', phonetic: 'cô-xi-nar', example: 'Hoy cocino yo.', exampleVi: 'Hôm nay tôi nấu.' },
      { id: 'ch3', spanish: 'Fregar', vietnamese: 'Rửa bát', phonetic: 'phrê-gar', example: 'Yo friego los platos.', exampleVi: 'Tôi rửa bát.' },
      { id: 'ch4', spanish: 'La lavadora', vietnamese: 'Máy giặt', phonetic: 'la la-ba-đô-ra', example: 'Pon la lavadora.', exampleVi: 'Bật máy giặt đi.' },
      { id: 'ch5', spanish: 'Tender la ropa', vietnamese: 'Phơi quần áo', phonetic: 'ten-đer la rô-pa', example: 'Tiende la ropa en el balcón.', exampleVi: 'Phơi quần áo ở ban công.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn phân chia việc nhà với gia đình.', vietnamese: '' },
      { role: 'ai', spanish: 'Hoy toca limpiar la casa. ¿Quién hace qué?', vietnamese: 'Hôm nay phải dọn nhà. Ai làm gì?', tip: '💡 "Toca + infinitivo" = Đến lúc phải... Rất tự nhiên trong gia đình.' },
      { role: 'user', spanish: 'Yo cocino. ¿Tú puedes fregar los platos?', vietnamese: 'Tôi nấu ăn. Bạn rửa bát được không?' },
      { role: 'ai', spanish: 'Vale, yo friego. Y los niños pueden barrer y tender la ropa.', vietnamese: 'OK, tôi rửa. Bọn trẻ quét nhà và phơi đồ.', suggestions: ['Perfecto, así terminamos pronto.', '¿Y quién pasa la aspiradora?', 'Los niños son muy pequeños para eso.'] },
    ],
  },
  {
    id: 'family-dinner',
    category: 'Gia đình', categoryEmoji: '🏠',
    title: 'Bữa tối gia đình',
    difficulty: 'Trung bình', xp: 45,
    culturalTip: '🇪🇸 Bữa tối TBN (la cena) thường nhẹ hơn bữa trưa: salad, tortilla, hoặc croquetas. Ăn lúc 21-22h là bình thường!',
    vocabulary: [
      { id: 'fd1b', spanish: 'La cena', vietnamese: 'Bữa tối', phonetic: 'la xê-na', example: '¿Qué hay para cenar?', exampleVi: 'Tối nay ăn gì?' },
      { id: 'fd2b', spanish: 'Poner la mesa', vietnamese: 'Dọn bàn ăn', phonetic: 'pô-ner la mê-xa', example: '¿Puedes poner la mesa?', exampleVi: 'Con dọn bàn được không?' },
      { id: 'fd3b', spanish: '¡A comer!', vietnamese: 'Ăn thôi!', phonetic: 'a cô-mer', example: '¡Niños, a comer!', exampleVi: 'Các con, ăn thôi!' },
      { id: 'fd4b', spanish: '¡Qué rico!', vietnamese: 'Ngon quá!', phonetic: 'kê ri-cô', example: '¡Qué rico está todo!', exampleVi: 'Mọi thứ ngon quá!' },
      { id: 'fd5b', spanish: '¿Quieres más?', vietnamese: 'Muốn thêm không?', phonetic: 'ki-ê-rét mát', example: '¿Quieres más ensalada?', exampleVi: 'Muốn thêm salad không?' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bữa tối gia đình tại nhà.', vietnamese: '' },
      { role: 'ai', spanish: '¡Niños, venid! ¡La cena está lista!', vietnamese: 'Các con, lại đây! Bữa tối sẵn rồi!', tip: '💡 "¡Venid!" là mệnh lệnh số nhiều ở TBN. Ở Latinh dùng "¡Vengan!"' },
      { role: 'user', spanish: '¡Qué bien huele! ¿Qué has preparado?', vietnamese: 'Thơm quá! Bạn nấu gì vậy?' },
      { role: 'ai', spanish: 'He preparado tortilla española con ensalada. ¿Quién pone la mesa?', vietnamese: 'Tôi làm tortilla TBN với salad. Ai dọn bàn?', suggestions: ['Yo pongo la mesa. ¿Dónde están los platos?', '¡Mmm, mi favorita! ¿Con cebolla o sin cebolla?', 'Los niños pueden poner la mesa hoy.'] },
    ],
  },

  // ═══════════════════════════════════════════
  // 🚗 DI CHUYỂN (Transport)
  // ═══════════════════════════════════════════
  {
    id: 'metro',
    category: 'Di chuyển', categoryEmoji: '🚗',
    title: 'Đi tàu điện ngầm',
    difficulty: 'Dễ', xp: 40,
    culturalTip: '🇪🇸 Metro Madrid là một trong những hệ thống tàu điện lớn nhất châu Âu! Vé 10 chuyến (Metrobús) tiết kiệm hơn mua lẻ.',
    vocabulary: [
      { id: 'mt1', spanish: 'La estación de metro', vietnamese: 'Trạm tàu điện', phonetic: 'la ét-ta-xi-ôn đê mê-trô', example: '¿Dónde está la estación de metro?', exampleVi: 'Trạm tàu ở đâu?' },
      { id: 'mt2', spanish: 'La línea', vietnamese: 'Tuyến', phonetic: 'la li-nê-a', example: 'Toma la línea 3.', exampleVi: 'Đi tuyến 3.' },
      { id: 'mt3', spanish: 'Transbordo', vietnamese: 'Chuyển tuyến', phonetic: 'tran-bor-đô', example: 'Haz transbordo en Sol.', exampleVi: 'Chuyển tuyến ở Sol.' },
      { id: 'mt4', spanish: 'La salida', vietnamese: 'Lối ra', phonetic: 'la xa-li-đa', example: '¿Cuál es la salida más cercana?', exampleVi: 'Lối ra gần nhất ở đâu?' },
      { id: 'mt5', spanish: 'El billete', vietnamese: 'Vé', phonetic: 'eo bi-giê-tê', example: 'Necesito un billete sencillo.', exampleVi: 'Tôi cần một vé đơn.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn cần đi metro ở Madrid đến bảo tàng Prado.', vietnamese: '' },
      { role: 'ai', spanish: 'Perdone, ¿sabe cómo llegar al Museo del Prado en metro?', vietnamese: 'Xin lỗi, bạn biết cách đi metro đến bảo tàng Prado không?', tip: '💡 "¿Sabe cómo llegar a...?" = Bạn biết cách đi đến...? Rất lịch sự.' },
      { role: 'user', spanish: 'Sí, tome la línea 1 dirección Valdecarros.', vietnamese: 'Có, đi tuyến 1 hướng Valdecarros.' },
      { role: 'ai', spanish: '¿En qué parada me bajo?', vietnamese: 'Tôi xuống trạm nào?', suggestions: ['Bájese en la parada Atocha.', '¿Tengo que hacer transbordo?', '¿Cuántas paradas son?'] },
    ],
  },
  {
    id: 'ask-directions',
    category: 'Di chuyển', categoryEmoji: '🚗',
    title: 'Hỏi đường',
    difficulty: 'Dễ', xp: 40,
    culturalTip: '🇪🇸 Người TBN rất thân thiện khi được hỏi đường! Đôi khi họ sẽ đi cùng bạn một đoạn để chỉ đường.',
    vocabulary: [
      { id: 'dir1', spanish: '¿Dónde está...?', vietnamese: '...ở đâu?', phonetic: 'đôn-đê ét-ta', example: '¿Dónde está la plaza?', exampleVi: 'Quảng trường ở đâu?' },
      { id: 'dir2', spanish: 'Girar a la derecha', vietnamese: 'Rẽ phải', phonetic: 'hi-rar a la đê-rê-cha', example: 'Gire a la derecha.', exampleVi: 'Rẽ phải.' },
      { id: 'dir3', spanish: 'Seguir recto', vietnamese: 'Đi thẳng', phonetic: 'xê-gir rếch-tô', example: 'Siga recto dos calles.', exampleVi: 'Đi thẳng 2 con đường.' },
      { id: 'dir4', spanish: 'Está cerca', vietnamese: 'Gần đây', phonetic: 'ét-ta xer-ca', example: 'No está lejos, está muy cerca.', exampleVi: 'Không xa, rất gần.' },
      { id: 'dir5', spanish: 'Al lado de', vietnamese: 'Bên cạnh', phonetic: 'ao la-đô đê', example: 'Está al lado del banco.', exampleVi: 'Bên cạnh ngân hàng.' },
      { id: 'dir6', spanish: 'Enfrente de', vietnamese: 'Đối diện', phonetic: 'en-phren-tê đê', example: 'Está enfrente de la iglesia.', exampleVi: 'Đối diện nhà thờ.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn đang đi bộ ở Madrid và bị lạc.', vietnamese: '' },
      { role: 'ai', spanish: '¡Hola! ¿Necesita ayuda? Parece perdido.', vietnamese: 'Xin chào! Cần giúp không? Có vẻ bạn bị lạc.', tip: '💡 "Parece perdido" = Có vẻ bị lạc. "Parece" + tính từ = có vẻ...' },
      { role: 'user', spanish: 'Sí, estoy buscando la Plaza Mayor.', vietnamese: 'Vâng, tôi đang tìm Plaza Mayor.' },
      { role: 'ai', spanish: 'Está muy cerca. Siga recto y gire a la izquierda en la segunda calle.', vietnamese: 'Rất gần. Đi thẳng, rẽ trái ở đường thứ 2.', suggestions: ['Muchas gracias. ¿Está lejos?', '¿Puede repetir, por favor?', '¿Hay algún restaurante cerca?'] },
    ],
  },
  {
    id: 'gas-station',
    category: 'Di chuyển', categoryEmoji: '🚗',
    title: 'Đổ xăng',
    difficulty: 'Trung bình', xp: 45,
    culturalTip: '🇪🇸 Ở TBN, nhiều trạm xăng tự phục vụ (autoservicio). "Gasolina" = xăng, "Gasóleo/Diésel" = dầu diesel.',
    vocabulary: [
      { id: 'gs1', spanish: 'La gasolinera', vietnamese: 'Trạm xăng', phonetic: 'la ga-xô-li-nê-ra', example: 'Necesito ir a la gasolinera.', exampleVi: 'Tôi cần đi đổ xăng.' },
      { id: 'gs2', spanish: 'Llenar el depósito', vietnamese: 'Đổ đầy bình', phonetic: 'giê-nar eo đê-pô-xi-tô', example: 'Llene el depósito, por favor.', exampleVi: 'Đổ đầy bình, làm ơn.' },
      { id: 'gs3', spanish: 'Gasolina sin plomo', vietnamese: 'Xăng không chì', phonetic: 'ga-xô-li-na xin plô-mô', example: 'Gasolina sin plomo 95.', exampleVi: 'Xăng không chì 95.' },
      { id: 'gs4', spanish: 'Pagar', vietnamese: 'Trả tiền', phonetic: 'pa-gar', example: '¿Dónde pago?', exampleVi: 'Trả tiền ở đâu?' },
      { id: 'gs5', spanish: 'El surtidor', vietnamese: 'Vòi bơm', phonetic: 'eo xur-ti-đor', example: 'Use el surtidor número 3.', exampleVi: 'Dùng vòi bơm số 3.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn dừng ở trạm xăng trên đường đi.', vietnamese: '' },
      { role: 'ai', spanish: '¡Buenas tardes! ¿Le lleno?', vietnamese: 'Chào! Đổ đầy không?', tip: '💡 "¿Le lleno?" = Đổ đầy không? Câu phổ biến ở trạm xăng có nhân viên.' },
      { role: 'user', spanish: 'Sí, llene el depósito de gasolina 95.', vietnamese: 'Vâng, đổ đầy xăng 95.' },
      { role: 'ai', spanish: 'Son cuarenta y cinco euros. ¿Efectivo o tarjeta?', vietnamese: 'Bốn mươi lăm euro. Tiền mặt hay thẻ?', suggestions: ['Con tarjeta, por favor.', 'En efectivo. Aquí tiene.', '¿Tienen servicio de lavado?'] },
    ],
  },
  {
    id: 'taxi-ride',
    category: 'Di chuyển', categoryEmoji: '🚗',
    title: 'Đi taxi',
    difficulty: 'Dễ', xp: 35,
    culturalTip: '🇪🇸 Taxi ở TBN có màu trắng với sọc đỏ/xanh. Có thể gọi bằng app FreeNow. Giá theo đồng hồ, tiền boa không bắt buộc.',
    vocabulary: [
      { id: 'tx1', spanish: 'Llevar a', vietnamese: 'Đưa đến', phonetic: 'giê-bar a', example: '¿Puede llevarme al aeropuerto?', exampleVi: 'Đưa tôi đến sân bay được không?' },
      { id: 'tx2', spanish: '¿Cuánto cuesta?', vietnamese: 'Giá bao nhiêu?', phonetic: 'coan-tô cuét-ta', example: '¿Cuánto cuesta hasta el centro?', exampleVi: 'Đến trung tâm bao nhiêu?' },
      { id: 'tx3', spanish: 'Pare aquí', vietnamese: 'Dừng ở đây', phonetic: 'pa-rê a-ki', example: 'Pare aquí, por favor.', exampleVi: 'Dừng đây, làm ơn.' },
      { id: 'tx4', spanish: 'El taxímetro', vietnamese: 'Đồng hồ taxi', phonetic: 'eo tac-xi-mê-trô', example: '¿Puede poner el taxímetro?', exampleVi: 'Bật đồng hồ được không?' },
      { id: 'tx5', spanish: 'Tengo prisa', vietnamese: 'Tôi vội', phonetic: 'ten-gô pri-xa', example: 'Tengo mucha prisa.', exampleVi: 'Tôi rất vội.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn bắt taxi ở Madrid.', vietnamese: '' },
      { role: 'ai', spanish: '¡Buenas! ¿Adónde le llevo?', vietnamese: 'Chào! Đi đâu?', tip: '💡 "¿Adónde?" = Đi đâu? Tài xế taxi thường nói "¿Adónde le llevo?"' },
      { role: 'user', spanish: 'Al aeropuerto, por favor. Tengo prisa.', vietnamese: 'Ra sân bay, làm ơn. Tôi vội.' },
      { role: 'ai', spanish: 'Muy bien. Por la autopista llegaremos en unos veinte minutos.', vietnamese: 'Được. Đi đường cao tốc khoảng 20 phút.', suggestions: ['¿Cuánto cuesta aproximadamente?', 'Perfecto, gracias.', '¿Puede ir más rápido?'] },
    ],
  },
  {
    id: 'airport',
    category: 'Di chuyển', categoryEmoji: '🚗',
    title: 'Ở sân bay',
    difficulty: 'Khó', xp: 65,
    culturalTip: '🇪🇸 Sân bay Madrid-Barajas (MAD) là sân bay lớn nhất TBN. Terminal 4 rất hiện đại. Luôn nói "Hola" trước khi nói gì với nhân viên!',
    vocabulary: [
      { id: 'ap1', spanish: 'La puerta de embarque', vietnamese: 'Cổng lên máy bay', phonetic: 'la puer-ta đê em-bar-kê', example: '¿Cuál es la puerta de embarque?', exampleVi: 'Cổng lên máy bay nào?' },
      { id: 'ap2', spanish: 'Facturar equipaje', vietnamese: 'Gửi hành lý', phonetic: 'phac-tu-rar ê-ki-pa-hê', example: 'Necesito facturar mi maleta.', exampleVi: 'Tôi cần gửi hành lý.' },
      { id: 'ap3', spanish: 'La tarjeta de embarque', vietnamese: 'Thẻ lên máy bay', phonetic: 'la tar-hê-ta đê em-bar-kê', example: 'Aquí tiene su tarjeta de embarque.', exampleVi: 'Đây là thẻ lên máy bay của bạn.' },
      { id: 'ap4', spanish: 'El vuelo', vietnamese: 'Chuyến bay', phonetic: 'eo bue-lô', example: 'Mi vuelo sale a las diez.', exampleVi: 'Chuyến bay tôi cất cánh lúc 10h.' },
      { id: 'ap5', spanish: 'Retraso', vietnamese: 'Trễ / Chậm', phonetic: 'rê-tra-xô', example: 'El vuelo tiene una hora de retraso.', exampleVi: 'Chuyến bay trễ 1 giờ.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn đang ở quầy check-in sân bay Madrid.', vietnamese: '' },
      { role: 'ai', spanish: 'Buenos días. ¿Me enseña su pasaporte y la reserva del vuelo?', vietnamese: 'Chào buổi sáng. Cho tôi xem hộ chiếu và đặt chỗ?', tip: '💡 "¿Me enseña...?" = Cho tôi xem...? Rất lịch sự ở sân bay.' },
      { role: 'user', spanish: 'Sí, aquí tiene. Vuelo a Barcelona.', vietnamese: 'Đây ạ. Bay đi Barcelona.' },
      { role: 'ai', spanish: '¿Quiere ventanilla o pasillo? ¿Tiene equipaje para facturar?', vietnamese: 'Muốn ghế cửa sổ hay lối đi? Có hành lý gửi không?', suggestions: ['Ventanilla, por favor. Tengo una maleta.', 'Pasillo. Solo llevo equipaje de mano.', '¿A qué hora es el embarque?'] },
    ],
  },

  // ═══════════════════════════════════════════
  // 💼 CÔNG VIỆC (Work)
  // ═══════════════════════════════════════════
  {
    id: 'self-intro-work',
    category: 'Công việc', categoryEmoji: '💼',
    title: 'Giới thiệu bản thân',
    difficulty: 'Dễ', xp: 40,
    culturalTip: '🇪🇸 Ở TBN, gặp nhau lần đầu thường bắt tay. Giữa bạn bè/gia đình thì hôn má (dos besos) — trái rồi phải!',
    vocabulary: [
      { id: 'si1', spanish: 'Me llamo...', vietnamese: 'Tôi tên...', phonetic: 'mê gia-mô', example: 'Me llamo Ana. Encantada.', exampleVi: 'Tôi tên Ana. Rất vui.' },
      { id: 'si2', spanish: 'Soy de...', vietnamese: 'Tôi từ...', phonetic: 'xôi đê', example: 'Soy de Vietnam.', exampleVi: 'Tôi từ Việt Nam.' },
      { id: 'si3', spanish: 'Trabajo como...', vietnamese: 'Tôi làm nghề...', phonetic: 'tra-ba-hô cô-mô', example: 'Trabajo como ingeniera.', exampleVi: 'Tôi làm kỹ sư.' },
      { id: 'si4', spanish: 'Encantado/a', vietnamese: 'Rất vui', phonetic: 'en-can-ta-đô', example: '¡Encantado de conocerte!', exampleVi: 'Rất vui được gặp bạn!' },
      { id: 'si5', spanish: 'Mi pasatiempo', vietnamese: 'Sở thích', phonetic: 'mi pa-xa-ti-em-pô', example: 'Mi pasatiempo es leer.', exampleVi: 'Sở thích tôi là đọc sách.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn gặp đồng nghiệp mới lần đầu.', vietnamese: '' },
      { role: 'ai', spanish: '¡Hola! Soy Carlos, del departamento de marketing. ¿Tú eres nuevo?', vietnamese: 'Chào! Tôi là Carlos, phòng marketing. Bạn mới à?', tip: '💡 "¿Tú eres nuevo/a?" = Bạn mới à? Thân thiện khi gặp đồng nghiệp mới.' },
      { role: 'user', spanish: '¡Hola Carlos! Sí, soy Linh. Empiezo hoy en el departamento de tecnología.', vietnamese: 'Chào Carlos! Đúng, tôi là Linh. Bắt đầu hôm nay ở phòng công nghệ.' },
      { role: 'ai', spanish: '¡Bienvenida, Linh! ¿De dónde eres?', vietnamese: 'Chào mừng, Linh! Bạn từ đâu?', suggestions: ['Soy de Vietnam. Vivo aquí desde hace un año.', 'Soy de Ho Chi Minh City.', '¿Cuánto tiempo llevas en la empresa?'] },
    ],
  },
  {
    id: 'work-meeting',
    category: 'Công việc', categoryEmoji: '💼',
    title: 'Họp nhóm',
    difficulty: 'Khó', xp: 70,
    culturalTip: '🇪🇸 Cuộc họp ở TBN thường bắt đầu trễ 5-10 phút. Nói chuyện phiếm trước khi vào việc là bình thường và được coi là lịch sự!',
    vocabulary: [
      { id: 'wm1', spanish: 'La reunión', vietnamese: 'Cuộc họp', phonetic: 'la rê-u-ni-ôn', example: 'Tenemos una reunión a las diez.', exampleVi: 'Chúng ta có họp lúc 10h.' },
      { id: 'wm2', spanish: 'El proyecto', vietnamese: 'Dự án', phonetic: 'eo prô-iếc-tô', example: '¿Cómo va el proyecto?', exampleVi: 'Dự án tiến triển thế nào?' },
      { id: 'wm3', spanish: 'La presentación', vietnamese: 'Bài thuyết trình', phonetic: 'la prê-xen-ta-xi-ôn', example: 'Voy a hacer una presentación.', exampleVi: 'Tôi sẽ thuyết trình.' },
      { id: 'wm4', spanish: 'El plazo', vietnamese: 'Hạn chót', phonetic: 'eo pla-xô', example: 'El plazo es el viernes.', exampleVi: 'Hạn chót là thứ Sáu.' },
      { id: 'wm5', spanish: 'Estoy de acuerdo', vietnamese: 'Tôi đồng ý', phonetic: 'ét-tôi đê a-cuer-đô', example: 'Estoy de acuerdo con tu propuesta.', exampleVi: 'Tôi đồng ý với đề xuất của bạn.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn đang họp nhóm với đồng nghiệp TBN.', vietnamese: '' },
      { role: 'ai', spanish: 'Buenos días a todos. Empezamos la reunión. ¿Cómo va el proyecto?', vietnamese: 'Chào mọi người. Bắt đầu họp. Dự án thế nào?', tip: '💡 "¿Cómo va?" = Thế nào rồi? Dùng hỏi tiến độ.' },
      { role: 'user', spanish: 'El proyecto va bien. Hemos terminado la primera fase.', vietnamese: 'Dự án ổn. Chúng tôi đã hoàn thành giai đoạn 1.' },
      { role: 'ai', spanish: 'Perfecto. ¿Cuáles son los próximos pasos? ¿Necesitáis algo?', vietnamese: 'Tuyệt. Bước tiếp theo là gì? Các bạn cần gì không?', suggestions: ['Necesitamos más tiempo para la segunda fase.', 'Estoy de acuerdo, podemos avanzar rápido.', '¿Cuál es el plazo para la siguiente fase?'] },
    ],
  },
  {
    id: 'spanish-email',
    category: 'Công việc', categoryEmoji: '💼',
    title: 'Viết email tiếng TBN',
    difficulty: 'Trung bình', xp: 55,
    culturalTip: '🇪🇸 Email trang trọng bắt đầu "Estimado/a" (Thân gửi) và kết thúc "Atentamente" hoặc "Un cordial saludo". Ít trang trọng: "Hola" và "Saludos".',
    vocabulary: [
      { id: 'em1', spanish: 'Estimado/a', vietnamese: 'Thân gửi (trang trọng)', phonetic: 'ét-ti-ma-đô', example: 'Estimado Sr. García:', exampleVi: 'Thân gửi ông García:' },
      { id: 'em2', spanish: 'Adjuntar', vietnamese: 'Đính kèm', phonetic: 'ađ-hun-tar', example: 'Adjunto el informe.', exampleVi: 'Tôi đính kèm báo cáo.' },
      { id: 'em3', spanish: 'Atentamente', vietnamese: 'Trân trọng', phonetic: 'a-ten-ta-men-tê', example: 'Atentamente, Ana López.', exampleVi: 'Trân trọng, Ana López.' },
      { id: 'em4', spanish: 'El asunto', vietnamese: 'Tiêu đề', phonetic: 'eo a-xun-tô', example: 'Asunto: Reunión del lunes.', exampleVi: 'Tiêu đề: Họp thứ Hai.' },
      { id: 'em5', spanish: 'Responder', vietnamese: 'Trả lời', phonetic: 'rết-pon-đer', example: 'Por favor, responda antes del viernes.', exampleVi: 'Vui lòng trả lời trước thứ Sáu.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn đang viết email cho đối tác TBN.', vietnamese: '' },
      { role: 'ai', spanish: '¿Cómo empiezo un email formal en español?', vietnamese: 'Bắt đầu email trang trọng bằng tiếng TBN thế nào?', tip: '💡 Trang trọng: "Estimado/a + tên". Bình thường: "Hola + tên".' },
      { role: 'user', spanish: 'Estimado Sr. Martínez, le escribo para confirmar la reunión del lunes.', vietnamese: 'Thân gửi ông Martínez, tôi viết để xác nhận cuộc họp thứ Hai.' },
      { role: 'ai', spanish: '¡Perfecto! ¿Quieres adjuntar algo? ¿Y cómo cierras el email?', vietnamese: 'Tuyệt! Muốn đính kèm gì không? Kết thúc email thế nào?', suggestions: ['Adjunto el informe. Atentamente, Linh.', 'Un cordial saludo, Linh Nguyen.', '¿Puedo usar "Saludos" o es demasiado informal?'] },
    ],
  },
  {
    id: 'job-interview',
    category: 'Công việc', categoryEmoji: '💼',
    title: 'Phỏng vấn xin việc',
    difficulty: 'Khó', xp: 80,
    culturalTip: '🇪🇸 Trong phỏng vấn ở TBN, dùng "usted" (trang trọng). Ăn mặc chỉnh tề, đến đúng giờ (hoặc sớm 5 phút).',
    vocabulary: [
      { id: 'ji1', spanish: 'El currículum', vietnamese: 'CV / Hồ sơ', phonetic: 'eo cu-rri-cu-lum', example: 'Aquí tiene mi currículum.', exampleVi: 'Đây là CV của tôi.' },
      { id: 'ji2', spanish: 'La experiencia', vietnamese: 'Kinh nghiệm', phonetic: 'la ếch-pê-ri-en-xi-a', example: 'Tengo cinco años de experiencia.', exampleVi: 'Tôi có 5 năm kinh nghiệm.' },
      { id: 'ji3', spanish: 'El puesto', vietnamese: 'Vị trí', phonetic: 'eo puết-tô', example: 'Estoy interesado en el puesto de...', exampleVi: 'Tôi quan tâm vị trí...' },
      { id: 'ji4', spanish: 'Mis puntos fuertes', vietnamese: 'Điểm mạnh của tôi', phonetic: 'mít pun-tốt phuer-tết', example: 'Mis puntos fuertes son...', exampleVi: 'Điểm mạnh của tôi là...' },
      { id: 'ji5', spanish: 'El salario', vietnamese: 'Lương', phonetic: 'eo xa-la-ri-ô', example: '¿Cuál es el salario?', exampleVi: 'Lương bao nhiêu?' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn đang phỏng vấn xin việc ở công ty TBN.', vietnamese: '' },
      { role: 'ai', spanish: 'Buenos días, siéntese. Cuénteme sobre usted.', vietnamese: 'Chào, mời ngồi. Kể cho tôi về bạn.', tip: '💡 "Cuénteme sobre usted" = Kể về bạn. Câu mở đầu phỏng vấn phổ biến nhất!' },
      { role: 'user', spanish: 'Buenos días. Me llamo Linh y tengo cinco años de experiencia en marketing digital.', vietnamese: 'Chào. Tôi tên Linh, có 5 năm kinh nghiệm marketing digital.' },
      { role: 'ai', spanish: 'Interesante. ¿Por qué le interesa este puesto?', vietnamese: 'Thú vị. Vì sao bạn quan tâm vị trí này?', suggestions: ['Me interesa porque quiero trabajar en un equipo internacional.', 'Me encanta el enfoque innovador de su empresa.', '¿Podría contarme más sobre las responsabilidades del puesto?'] },
    ],
  },
  {
    id: 'with-colleagues',
    category: 'Công việc', categoryEmoji: '💼',
    title: 'Trò chuyện với đồng nghiệp',
    difficulty: 'Trung bình', xp: 50,
    culturalTip: '🇪🇸 "¿Tomamos un café?" (Uống cà phê không?) là cách phổ biến rủ đồng nghiệp nghỉ giải lao. Giờ cà phê rất quan trọng!',
    vocabulary: [
      { id: 'wc1', spanish: '¿Tomamos un café?', vietnamese: 'Uống cà phê không?', phonetic: 'tô-ma-mốt un ca-phê', example: '¿Tomamos un café? Necesito un descanso.', exampleVi: 'Uống cà phê không? Tôi cần nghỉ.' },
      { id: 'wc2', spanish: 'El descanso', vietnamese: 'Giờ nghỉ', phonetic: 'eo đết-can-xô', example: '¿Cuándo es el descanso?', exampleVi: 'Giờ nghỉ khi nào?' },
      { id: 'wc3', spanish: '¿Qué tal el fin de semana?', vietnamese: 'Cuối tuần thế nào?', phonetic: 'kê tal eo phin đê xê-ma-na', example: '¡Hola! ¿Qué tal el fin de semana?', exampleVi: 'Chào! Cuối tuần sao?' },
      { id: 'wc4', spanish: 'Echar una mano', vietnamese: 'Giúp một tay', phonetic: 'ê-char u-na ma-nô', example: '¿Te echo una mano con eso?', exampleVi: 'Tôi giúp bạn cái đó nhé?' },
      { id: 'wc5', spanish: '¡Buen trabajo!', vietnamese: 'Làm tốt lắm!', phonetic: 'buen tra-ba-hô', example: '¡Buen trabajo en la presentación!', exampleVi: 'Thuyết trình tốt lắm!' },
    ],
    conversation: [
      { role: 'system', spanish: 'Giờ nghỉ trưa, bạn nói chuyện với đồng nghiệp.', vietnamese: '' },
      { role: 'ai', spanish: '¡Hola Linh! ¿Tomamos un café? ¿Qué tal el fin de semana?', vietnamese: 'Chào Linh! Uống cà phê không? Cuối tuần sao?', tip: '💡 Người TBN hay hỏi cuối tuần thế nào vào thứ Hai. Chuẩn bị sẵn câu trả lời!' },
      { role: 'user', spanish: '¡Hola! Sí, un café estaría genial. El fin de semana fue muy bueno.', vietnamese: 'Chào! Ừ, cà phê hay đó. Cuối tuần vui lắm.' },
      { role: 'ai', spanish: '¿Qué hiciste? ¿Fuiste a algún sitio?', vietnamese: 'Bạn làm gì? Đi đâu không?', suggestions: ['Fui al parque con mi familia.', 'Me quedé en casa, descansando.', '¿Y tú? ¿Qué hiciste?'] },
    ],
  },

  // ═══════════════════════════════════════════
  // 🏥 SỨC KHỎE (Health)
  // ═══════════════════════════════════════════
  {
    id: 'doctor-visit',
    category: 'Sức khỏe', categoryEmoji: '🏥',
    title: 'Đi khám bác sĩ',
    difficulty: 'Trung bình', xp: 55,
    culturalTip: '🇪🇸 TBN có hệ thống y tế công tốt. Nếu bạn có "tarjeta sanitaria" (thẻ bảo hiểm y tế), khám bệnh miễn phí!',
    vocabulary: [
      { id: 'dr1', spanish: 'Me duele...', vietnamese: 'Tôi đau...', phonetic: 'mê đue-lê', example: 'Me duele la cabeza.', exampleVi: 'Tôi đau đầu.' },
      { id: 'dr2', spanish: 'Tengo fiebre', vietnamese: 'Tôi bị sốt', phonetic: 'ten-gô phi-ê-brê', example: 'Tengo fiebre desde ayer.', exampleVi: 'Tôi bị sốt từ hôm qua.' },
      { id: 'dr3', spanish: 'La cita', vietnamese: 'Lịch hẹn', phonetic: 'la xi-ta', example: 'Tengo una cita con el doctor.', exampleVi: 'Tôi có hẹn với bác sĩ.' },
      { id: 'dr4', spanish: 'La receta', vietnamese: 'Đơn thuốc', phonetic: 'la rê-xê-ta', example: 'Le voy a dar una receta.', exampleVi: 'Tôi sẽ kê đơn cho bạn.' },
      { id: 'dr5', spanish: 'Alérgico/a a', vietnamese: 'Dị ứng với', phonetic: 'a-lér-hi-cô a', example: 'Soy alérgico a la penicilina.', exampleVi: 'Tôi dị ứng penicillin.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn đi khám bác sĩ vì bị cảm.', vietnamese: '' },
      { role: 'ai', spanish: 'Buenos días. ¿Qué le pasa?', vietnamese: 'Chào. Bạn bị sao?', tip: '💡 "¿Qué le pasa?" = Bạn bị sao? Bác sĩ luôn hỏi câu này đầu tiên.' },
      { role: 'user', spanish: 'Me duele la garganta y tengo tos.', vietnamese: 'Tôi đau họng và bị ho.' },
      { role: 'ai', spanish: '¿Desde cuándo tiene estos síntomas? ¿Tiene fiebre?', vietnamese: 'Bị từ bao giờ? Có sốt không?', suggestions: ['Desde hace tres días. Sí, tengo un poco de fiebre.', 'Desde ayer. No tengo fiebre.', '¿Es algo grave, doctor?'] },
    ],
  },
  {
    id: 'pharmacy-health',
    category: 'Sức khỏe', categoryEmoji: '🏥',
    title: 'Mua thuốc ở nhà thuốc',
    difficulty: 'Dễ', xp: 40,
    culturalTip: '🇪🇸 Dược sĩ ở TBN rất chuyên nghiệp và có thể tư vấn bệnh nhẹ mà không cần đi bác sĩ. Tiết kiệm thời gian!',
    vocabulary: [
      { id: 'phh1', spanish: 'El jarabe', vietnamese: 'Siro', phonetic: 'eo ha-ra-bê', example: 'Necesito un jarabe para la tos.', exampleVi: 'Tôi cần siro ho.' },
      { id: 'phh2', spanish: 'Las tiritas', vietnamese: 'Băng cá nhân', phonetic: 'lát ti-ri-tát', example: '¿Tiene tiritas?', exampleVi: 'Có băng cá nhân không?' },
      { id: 'phh3', spanish: 'El ibuprofeno', vietnamese: 'Ibuprofen', phonetic: 'eo i-bu-prô-phê-nô', example: 'Quiero ibuprofeno.', exampleVi: 'Tôi muốn mua ibuprofen.' },
      { id: 'phh4', spanish: 'Cada ocho horas', vietnamese: 'Mỗi 8 giờ', phonetic: 'ca-đa ô-chô ô-rát', example: 'Tome una pastilla cada ocho horas.', exampleVi: 'Uống 1 viên mỗi 8 giờ.' },
      { id: 'phh5', spanish: 'Antes de las comidas', vietnamese: 'Trước bữa ăn', phonetic: 'an-tết đê lát cô-mi-đát', example: 'Tome esto antes de las comidas.', exampleVi: 'Uống trước bữa ăn.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn bị cảm nhẹ và đến hiệu thuốc.', vietnamese: '' },
      { role: 'ai', spanish: '¡Buenas tardes! ¿En qué puedo ayudarle?', vietnamese: 'Chào! Tôi giúp gì được?', tip: '💡 Dược sĩ TBN có thể tư vấn bệnh nhẹ, không cần đi bác sĩ!' },
      { role: 'user', spanish: 'Tengo dolor de cabeza y un poco de tos.', vietnamese: 'Tôi đau đầu và ho nhẹ.' },
      { role: 'ai', spanish: 'Le recomiendo ibuprofeno para el dolor y un jarabe para la tos. ¿Es alérgico a algo?', vietnamese: 'Tôi khuyên ibuprofen cho đau và siro cho ho. Bạn dị ứng gì không?', suggestions: ['No, no soy alérgico a nada.', '¿Cuántas pastillas tomo al día?', '¿Necesito receta para estos medicamentos?'] },
    ],
  },
  {
    id: 'describe-symptoms',
    category: 'Sức khỏe', categoryEmoji: '🏥',
    title: 'Mô tả triệu chứng',
    difficulty: 'Trung bình', xp: 50,
    culturalTip: '🇪🇸 "Me encuentro mal" (Tôi thấy không khỏe) là cách tổng quát nói bạn bị ốm. Hữu ích khi chưa biết mô tả cụ thể!',
    vocabulary: [
      { id: 'sy1', spanish: 'Me encuentro mal', vietnamese: 'Tôi không khỏe', phonetic: 'mê en-cuen-trô mal', example: 'Me encuentro mal desde ayer.', exampleVi: 'Tôi không khỏe từ hôm qua.' },
      { id: 'sy2', spanish: 'Mareos', vietnamese: 'Chóng mặt', phonetic: 'ma-rê-ốt', example: 'Tengo mareos.', exampleVi: 'Tôi bị chóng mặt.' },
      { id: 'sy3', spanish: 'Náuseas', vietnamese: 'Buồn nôn', phonetic: 'na-u-xê-át', example: 'Tengo náuseas.', exampleVi: 'Tôi buồn nôn.' },
      { id: 'sy4', spanish: 'Me duele el estómago', vietnamese: 'Đau bụng', phonetic: 'mê đue-lê eo ết-tô-ma-gô', example: 'Me duele mucho el estómago.', exampleVi: 'Tôi đau bụng lắm.' },
      { id: 'sy5', spanish: 'Estornudar', vietnamese: 'Hắt hơi', phonetic: 'ết-tor-nu-đar', example: 'No paro de estornudar.', exampleVi: 'Tôi hắt hơi liên tục.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn gọi điện cho bác sĩ mô tả triệu chứng.', vietnamese: '' },
      { role: 'ai', spanish: 'Consulta médica, dígame. ¿Qué síntomas tiene?', vietnamese: 'Phòng khám xin nghe. Bạn có triệu chứng gì?', tip: '💡 "Dígame" = Xin nghe. Cách trả lời điện thoại phổ biến ở TBN.' },
      { role: 'user', spanish: 'Me encuentro mal. Tengo fiebre, tos y me duele la garganta.', vietnamese: 'Tôi không khỏe. Sốt, ho và đau họng.' },
      { role: 'ai', spanish: '¿Desde cuándo? ¿Ha tomado algo?', vietnamese: 'Từ bao giờ? Đã uống thuốc gì chưa?', suggestions: ['Desde anteayer. He tomado paracetamol.', '¿Puedo pedir una cita para hoy?', '¿Cree que es grave?'] },
    ],
  },
  {
    id: 'emergency',
    category: 'Sức khỏe', categoryEmoji: '🏥',
    title: 'Trường hợp khẩn cấp',
    difficulty: 'Khó', xp: 65,
    culturalTip: '🇪🇸 Số khẩn cấp ở TBN và châu Âu: 112. Nói chậm, rõ, và cho địa chỉ. "¡Es una emergencia!" = Đây là trường hợp khẩn cấp!',
    vocabulary: [
      { id: 'er1', spanish: '¡Emergencia!', vietnamese: 'Khẩn cấp!', phonetic: 'ê-mer-hen-xi-a', example: '¡Es una emergencia! Llame al 112.', exampleVi: 'Khẩn cấp! Gọi 112.' },
      { id: 'er2', spanish: 'La ambulancia', vietnamese: 'Xe cấp cứu', phonetic: 'la am-bu-lan-xi-a', example: 'Necesitamos una ambulancia.', exampleVi: 'Chúng tôi cần xe cấp cứu.' },
      { id: 'er3', spanish: 'Urgencias', vietnamese: 'Phòng cấp cứu', phonetic: 'ur-hen-xi-át', example: '¿Dónde están las urgencias?', exampleVi: 'Phòng cấp cứu ở đâu?' },
      { id: 'er4', spanish: 'Se ha caído', vietnamese: 'Bị ngã', phonetic: 'xê a ca-i-đô', example: 'Se ha caído y no puede levantarse.', exampleVi: 'Bị ngã và không đứng dậy được.' },
      { id: 'er5', spanish: 'Necesito ayuda', vietnamese: 'Tôi cần giúp đỡ', phonetic: 'nê-xê-xi-tô a-iu-đa', example: '¡Por favor, necesito ayuda!', exampleVi: 'Làm ơn, tôi cần giúp!' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn cần gọi cấp cứu.', vietnamese: '' },
      { role: 'ai', spanish: 'Emergencias 112, ¿qué ha ocurrido?', vietnamese: 'Cấp cứu 112, có chuyện gì?', tip: '💡 Khi gọi 112: 1) Nói chuyện gì xảy ra. 2) Cho địa chỉ. 3) Nói số điện thoại bạn.' },
      { role: 'user', spanish: 'Mi padre se ha caído y le duele mucho la pierna. No puede caminar.', vietnamese: 'Ba tôi bị ngã và đau chân lắm. Không đi được.' },
      { role: 'ai', spanish: '¿Cuál es la dirección? Enviamos una ambulancia inmediatamente.', vietnamese: 'Địa chỉ ở đâu? Chúng tôi gửi xe cấp cứu ngay.', suggestions: ['Estamos en la calle Gran Vía, número 45.', '¿Cuánto tarda la ambulancia?', '¿Qué puedo hacer mientras tanto?'] },
    ],
  },
  {
    id: 'dentist',
    category: 'Sức khỏe', categoryEmoji: '🏥',
    title: 'Đi nha sĩ',
    difficulty: 'Trung bình', xp: 50,
    culturalTip: '🇪🇸 Nha sĩ ở TBN thường là tư nhân, không nằm trong bảo hiểm công. Giá niềng răng khoảng 2000-5000€.',
    vocabulary: [
      { id: 'dn1', spanish: 'El dentista', vietnamese: 'Nha sĩ', phonetic: 'eo đen-tit-ta', example: 'Tengo cita con el dentista.', exampleVi: 'Tôi có hẹn với nha sĩ.' },
      { id: 'dn2', spanish: 'Me duele una muela', vietnamese: 'Đau răng hàm', phonetic: 'mê đue-lê u-na mue-la', example: 'Me duele mucho una muela.', exampleVi: 'Tôi đau răng hàm lắm.' },
      { id: 'dn3', spanish: 'La caries', vietnamese: 'Sâu răng', phonetic: 'la ca-ri-ét', example: 'Tiene una caries.', exampleVi: 'Bạn bị sâu răng.' },
      { id: 'dn4', spanish: 'Empastar', vietnamese: 'Trám răng', phonetic: 'em-pat-tar', example: 'Hay que empastar esta muela.', exampleVi: 'Phải trám răng này.' },
      { id: 'dn5', spanish: 'Abra la boca', vietnamese: 'Mở miệng', phonetic: 'a-bra la bô-ca', example: 'Abra la boca, por favor.', exampleVi: 'Mở miệng ra.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn đi khám nha sĩ vì đau răng.', vietnamese: '' },
      { role: 'ai', spanish: 'Buenas tardes. Siéntese. ¿Qué le pasa?', vietnamese: 'Chào. Mời ngồi. Bạn bị sao?', tip: '💡 "Siéntese" = Mời ngồi. Dạng lịch sự của "siéntate".' },
      { role: 'user', spanish: 'Me duele mucho una muela. No puedo masticar.', vietnamese: 'Tôi đau răng hàm lắm. Không nhai được.' },
      { role: 'ai', spanish: 'Vamos a ver. Abra la boca. Mmm, tiene una caries. Hay que empastar.', vietnamese: 'Xem nào. Mở miệng. Hmm, sâu răng. Phải trám.', suggestions: ['¿Duele mucho el empaste?', '¿Cuánto cuesta?', '¿Tengo que volver para otra cita?'] },
    ],
  },

  // ═══════════════════════════════════════════
  // 🎉 XÃ HỘI (Social)
  // ═══════════════════════════════════════════
  {
    id: 'meet-new-people',
    category: 'Xã hội', categoryEmoji: '🎉',
    title: 'Gặp người mới',
    difficulty: 'Dễ', xp: 35,
    culturalTip: '🇪🇸 Hai nụ hôn má (dos besos) là cách chào giữa bạn bè ở TBN. Má trái trước! Giữa nam-nam thì bắt tay.',
    vocabulary: [
      { id: 'mn1', spanish: '¿Cómo te llamas?', vietnamese: 'Bạn tên gì?', phonetic: 'cô-mô tê gia-mát', example: '¡Hola! ¿Cómo te llamas?', exampleVi: 'Xin chào! Bạn tên gì?' },
      { id: 'mn2', spanish: 'Encantado/a', vietnamese: 'Rất vui', phonetic: 'en-can-ta-đô', example: 'Encantada de conocerte.', exampleVi: 'Rất vui được gặp bạn.' },
      { id: 'mn3', spanish: '¿A qué te dedicas?', vietnamese: 'Bạn làm nghề gì?', phonetic: 'a kê tê đê-đi-cát', example: '¿A qué te dedicas?', exampleVi: 'Bạn làm nghề gì?' },
      { id: 'mn4', spanish: '¿De dónde eres?', vietnamese: 'Bạn từ đâu?', phonetic: 'đê đôn-đê ê-rét', example: '¿De dónde eres?', exampleVi: 'Bạn từ đâu?' },
      { id: 'mn5', spanish: '¡Qué interesante!', vietnamese: 'Thú vị quá!', phonetic: 'kê in-tê-rê-xan-tê', example: '¡Qué interesante! Cuéntame más.', exampleVi: 'Thú vị quá! Kể thêm đi.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn gặp người mới ở buổi tiệc.', vietnamese: '' },
      { role: 'ai', spanish: '¡Hola! Soy María. ¡Dos besos! ¿Cómo te llamas?', vietnamese: 'Xin chào! Tôi là María. Hôn má nhé! Bạn tên gì?', tip: '💡 "Dos besos" = hai nụ hôn má. Cách chào thân thiện ở TBN.' },
      { role: 'user', spanish: '¡Hola María! Me llamo Linh. Encantada.', vietnamese: 'Chào María! Tôi tên Linh. Rất vui.' },
      { role: 'ai', spanish: '¿De dónde eres, Linh? ¿Cuánto tiempo llevas en España?', vietnamese: 'Bạn từ đâu, Linh? Ở TBN bao lâu rồi?', suggestions: ['Soy de Vietnam. Llevo un año aquí.', '¿Y tú? ¿Eres de aquí?', '¡Me encanta España! La comida es increíble.'] },
    ],
  },
  {
    id: 'party-invite',
    category: 'Xã hội', categoryEmoji: '🎉',
    title: 'Mời đi tiệc',
    difficulty: 'Dễ', xp: 40,
    culturalTip: '🇪🇸 Tiệc ở TBN bắt đầu muộn! Nếu mời 21h, người TBN sẽ đến 21:30-22h. Luôn mang gì đó (rượu, bánh) khi đến nhà ai.',
    vocabulary: [
      { id: 'pi1', spanish: '¿Vienes a la fiesta?', vietnamese: 'Đến tiệc không?', phonetic: 'bi-ê-nêt a la phi-ết-ta', example: '¿Vienes a la fiesta el sábado?', exampleVi: 'Thứ Bảy đến tiệc không?' },
      { id: 'pi2', spanish: '¡Claro que sí!', vietnamese: 'Tất nhiên!', phonetic: 'cla-rô kê xi', example: '¡Claro que sí! ¿Llevo algo?', exampleVi: 'Tất nhiên! Mang gì đi?' },
      { id: 'pi3', spanish: 'Una botella de vino', vietnamese: 'Một chai rượu', phonetic: 'u-na bô-tê-gia đê bi-nô', example: 'Llevo una botella de vino.', exampleVi: 'Tôi mang chai rượu.' },
      { id: 'pi4', spanish: '¿A qué hora?', vietnamese: 'Mấy giờ?', phonetic: 'a kê ô-ra', example: '¿A qué hora empieza la fiesta?', exampleVi: 'Tiệc bắt đầu mấy giờ?' },
      { id: 'pi5', spanish: '¿Puedo llevar a alguien?', vietnamese: 'Mang thêm ai được không?', phonetic: 'puê-đô giê-bar a al-gi-en', example: '¿Puedo llevar a un amigo?', exampleVi: 'Mang theo bạn được không?' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn mời bạn TBN đến tiệc sinh nhật.', vietnamese: '' },
      { role: 'ai', spanish: '¡Oye, Linh! ¿Qué planes tienes el sábado?', vietnamese: 'Ê Linh! Thứ Bảy có kế hoạch gì?', tip: '💡 "¡Oye!" = Ê! Cách gọi bạn bè thân thiện.' },
      { role: 'user', spanish: '¡Hola! Es mi cumpleaños. ¿Vienes a la fiesta?', vietnamese: 'Chào! Sinh nhật tôi. Đến tiệc không?' },
      { role: 'ai', spanish: '¡Felicidades! ¡Claro que sí! ¿A qué hora? ¿Llevo algo?', vietnamese: 'Chúc mừng! Tất nhiên! Mấy giờ? Mang gì đi?', suggestions: ['A las nueve. Trae algo de beber.', 'No te preocupes, solo ven. A las ocho.', '¿Puedes traer tu guitarra?'] },
    ],
  },
  {
    id: 'make-plans',
    category: 'Xã hội', categoryEmoji: '🎉',
    title: 'Lên kế hoạch đi chơi',
    difficulty: 'Trung bình', xp: 45,
    culturalTip: '🇪🇸 "Quedamos" = Hẹn gặp nhé. "¿Quedamos a las...?" rất phổ biến khi hẹn bạn bè. Người TBN hay linh hoạt về giờ!',
    vocabulary: [
      { id: 'mp1', spanish: '¿Quedamos?', vietnamese: 'Hẹn gặp nhé?', phonetic: 'kê-đa-mốt', example: '¿Quedamos mañana?', exampleVi: 'Ngày mai hẹn gặp nhé?' },
      { id: 'mp2', spanish: '¿Te apetece...?', vietnamese: 'Bạn thích... không?', phonetic: 'tê a-pê-tê-xê', example: '¿Te apetece ir al cine?', exampleVi: 'Thích đi xem phim không?' },
      { id: 'mp3', spanish: 'Depende', vietnamese: 'Tùy', phonetic: 'đê-pen-đê', example: 'Depende del tiempo.', exampleVi: 'Tùy thời tiết.' },
      { id: 'mp4', spanish: 'No puedo', vietnamese: 'Tôi không được', phonetic: 'nô puê-đô', example: 'Lo siento, no puedo el viernes.', exampleVi: 'Xin lỗi, thứ Sáu tôi không được.' },
      { id: 'mp5', spanish: '¿Qué te parece...?', vietnamese: 'Bạn nghĩ sao về...?', phonetic: 'kê tê pa-rê-xê', example: '¿Qué te parece ir a la playa?', exampleVi: 'Đi biển thì sao?' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn và bạn TBN lên kế hoạch cuối tuần.', vietnamese: '' },
      { role: 'ai', spanish: '¡Oye! ¿Quedamos este fin de semana? ¿Te apetece hacer algo?', vietnamese: 'Ê! Cuối tuần gặp nhau không? Muốn làm gì không?', tip: '💡 "¿Te apetece?" = Bạn thích/muốn không? Rất tự nhiên trong TBN.' },
      { role: 'user', spanish: '¡Sí! ¿Qué te parece ir al cine el sábado?', vietnamese: 'Ừ! Thứ Bảy đi xem phim sao?' },
      { role: 'ai', spanish: '¡Buena idea! ¿A qué hora quedamos? ¿En el centro?', vietnamese: 'Hay đó! Mấy giờ hẹn? Ở trung tâm?', suggestions: ['¿Quedamos a las cinco en la puerta del cine?', '¿Hay alguna peli buena?', 'Prefiero ir el domingo, ¿te va bien?'] },
    ],
  },
  {
    id: 'compliments',
    category: 'Xã hội', categoryEmoji: '🎉',
    title: 'Khen ngợi',
    difficulty: 'Dễ', xp: 35,
    culturalTip: '🇪🇸 Người TBN rất hay khen! "¡Qué guapo/a!" (Đẹp trai/gái quá!), "¡Qué bonito!" (Đẹp quá!) rất phổ biến trong giao tiếp hàng ngày.',
    vocabulary: [
      { id: 'cp1', spanish: '¡Qué bonito!', vietnamese: 'Đẹp quá!', phonetic: 'kê bô-ni-tô', example: '¡Qué bonita tu casa!', exampleVi: 'Nhà bạn đẹp quá!' },
      { id: 'cp2', spanish: '¡Qué bien!', vietnamese: 'Tuyệt quá!', phonetic: 'kê bi-en', example: '¡Qué bien cocinas!', exampleVi: 'Bạn nấu ăn giỏi quá!' },
      { id: 'cp3', spanish: 'Me encanta', vietnamese: 'Tôi rất thích', phonetic: 'mê en-can-ta', example: 'Me encanta tu vestido.', exampleVi: 'Tôi rất thích váy bạn.' },
      { id: 'cp4', spanish: '¡Qué guapo/a!', vietnamese: 'Đẹp trai/gái quá!', phonetic: 'kê gua-pô', example: '¡Qué guapa estás hoy!', exampleVi: 'Hôm nay bạn xinh quá!' },
      { id: 'cp5', spanish: 'Tienes muy buen gusto', vietnamese: 'Bạn có gu tốt', phonetic: 'ti-ê-nêt muy buen gút-tô', example: 'Tienes muy buen gusto para la ropa.', exampleVi: 'Bạn có gu ăn mặc tốt.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn khen bạn TBN về nhà mới của họ.', vietnamese: '' },
      { role: 'ai', spanish: '¡Bienvenida a mi casa nueva! ¿Qué te parece?', vietnamese: 'Chào mừng đến nhà mới! Thế nào?', tip: '💡 "¿Qué te parece?" = Bạn nghĩ sao? Dùng hỏi ý kiến về mọi thứ.' },
      { role: 'user', spanish: '¡Qué bonita! Me encanta la decoración.', vietnamese: 'Đẹp quá! Tôi rất thích cách trang trí.' },
      { role: 'ai', spanish: '¡Gracias! Hemos tardado mucho en decorarla. ¿Quieres ver la terraza?', vietnamese: 'Cảm ơn! Chúng tôi trang trí lâu lắm. Muốn xem ban công không?', suggestions: ['¡Sí! Me encantaría. ¡Qué vista!', '¡Tienes muy buen gusto!', '¿Dónde compraste estos muebles?'] },
    ],
  },
  {
    id: 'apologies',
    category: 'Xã hội', categoryEmoji: '🎉',
    title: 'Xin lỗi',
    difficulty: 'Trung bình', xp: 45,
    culturalTip: '🇪🇸 "Perdona" (thân mật) vs "Perdone" (lịch sự). "Lo siento" nặng hơn, dùng khi thực sự có lỗi. "Disculpa" ở giữa.',
    vocabulary: [
      { id: 'ap1b', spanish: 'Lo siento', vietnamese: 'Tôi xin lỗi', phonetic: 'lô xi-en-tô', example: 'Lo siento mucho.', exampleVi: 'Tôi rất xin lỗi.' },
      { id: 'ap2b', spanish: 'Perdona', vietnamese: 'Xin lỗi (thân mật)', phonetic: 'per-đô-na', example: 'Perdona, no fue mi intención.', exampleVi: 'Xin lỗi, không phải ý tôi.' },
      { id: 'ap3b', spanish: 'No pasa nada', vietnamese: 'Không sao', phonetic: 'nô pa-xa na-đa', example: '¡No pasa nada! No te preocupes.', exampleVi: 'Không sao! Đừng lo.' },
      { id: 'ap4b', spanish: 'Ha sido culpa mía', vietnamese: 'Lỗi của tôi', phonetic: 'a xi-đô cul-pa mi-a', example: 'Ha sido culpa mía. Lo siento.', exampleVi: 'Lỗi của tôi. Xin lỗi.' },
      { id: 'ap5b', spanish: 'Te pido disculpas', vietnamese: 'Tôi xin lỗi bạn', phonetic: 'tê pi-đô đít-cul-pát', example: 'Te pido disculpas por llegar tarde.', exampleVi: 'Tôi xin lỗi vì đến trễ.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn đến trễ buổi hẹn với bạn.', vietnamese: '' },
      { role: 'ai', spanish: '¡Llegas veinte minutos tarde! Te he estado esperando.', vietnamese: 'Bạn trễ 20 phút! Tôi đợi hoài.', tip: '💡 "Llegas tarde" = Bạn đến trễ. "Te he estado esperando" = Tôi đã đợi bạn.' },
      { role: 'user', spanish: '¡Lo siento mucho! He perdido el autobús.', vietnamese: 'Xin lỗi nhiều! Tôi lỡ xe buýt.' },
      { role: 'ai', spanish: 'Bueno, no pasa nada. ¿Entramos? Ya tenemos mesa.', vietnamese: 'Thôi, không sao. Vào nhé? Có bàn rồi.', suggestions: ['Gracias por esperarme. La próxima vez llego puntual.', 'Te invito a cenar para compensar.', '¡Perdona de verdad! No volverá a pasar.'] },
    ],
  },

  // ═══════════════════════════════════════════
  // 📱 CÔNG NGHỆ (Tech)
  // ═══════════════════════════════════════════
  {
    id: 'social-media',
    category: 'Công nghệ', categoryEmoji: '📱',
    title: 'Mạng xã hội',
    difficulty: 'Dễ', xp: 35,
    culturalTip: '🇪🇸 Instagram và TikTok rất phổ biến ở TBN. "Sígueme" = Follow tôi nhé. Hashtag bằng tiếng TBN rất phổ biến!',
    vocabulary: [
      { id: 'sm1', spanish: 'Dar me gusta', vietnamese: 'Like / Thích', phonetic: 'đar mê gút-ta', example: 'Le di me gusta a tu foto.', exampleVi: 'Tôi đã like ảnh bạn.' },
      { id: 'sm2', spanish: 'Seguir', vietnamese: 'Theo dõi / Follow', phonetic: 'xê-gir', example: '¿Me sigues en Instagram?', exampleVi: 'Bạn follow tôi trên Instagram không?' },
      { id: 'sm3', spanish: 'Publicar', vietnamese: 'Đăng', phonetic: 'pu-bli-car', example: 'Voy a publicar esta foto.', exampleVi: 'Tôi sẽ đăng ảnh này.' },
      { id: 'sm4', spanish: 'Compartir', vietnamese: 'Chia sẻ', phonetic: 'com-par-tir', example: '¿Puedo compartir esto?', exampleVi: 'Tôi chia sẻ cái này được không?' },
      { id: 'sm5', spanish: 'El perfil', vietnamese: 'Trang cá nhân', phonetic: 'eo per-phil', example: 'Tu perfil es muy bonito.', exampleVi: 'Trang cá nhân bạn đẹp.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn nói chuyện với bạn TBN về mạng xã hội.', vietnamese: '' },
      { role: 'ai', spanish: '¿Tienes Instagram? ¡Sígueme! Soy @maria_madrid.', vietnamese: 'Bạn có Instagram không? Follow tôi đi! Tôi là @maria_madrid.', tip: '💡 "¡Sígueme!" = Follow tôi! Người TBN hay trao đổi mạng xã hội khi gặp nhau.' },
      { role: 'user', spanish: '¡Sí! Ya te sigo. Me encantan tus fotos de comida.', vietnamese: 'Có! Tôi đã follow rồi. Tôi rất thích ảnh đồ ăn của bạn.' },
      { role: 'ai', spanish: '¡Gracias! Publico una foto cada día. ¿Tú también publicas mucho?', vietnamese: 'Cảm ơn! Tôi đăng 1 ảnh mỗi ngày. Bạn cũng đăng nhiều không?', suggestions: ['Sí, sobre todo fotos de viajes.', 'No mucho, solo miro las fotos de otros.', '¿Usas también TikTok?'] },
    ],
  },
  {
    id: 'online-shopping-tech',
    category: 'Công nghệ', categoryEmoji: '📱',
    title: 'Mua hàng online',
    difficulty: 'Trung bình', xp: 45,
    culturalTip: '🇪🇸 Amazon, El Corte Inglés online, và Wallapop (đồ secondhand) rất phổ biến ở TBN. Black Friday cũng là sự kiện lớn!',
    vocabulary: [
      { id: 'os1', spanish: 'Añadir al carrito', vietnamese: 'Thêm vào giỏ', phonetic: 'a-nha-đir ao ca-rri-tô', example: 'Añade esto al carrito.', exampleVi: 'Thêm cái này vào giỏ.' },
      { id: 'os2', spanish: 'El envío', vietnamese: 'Giao hàng', phonetic: 'eo en-bi-ô', example: 'El envío es gratis.', exampleVi: 'Giao hàng miễn phí.' },
      { id: 'os3', spanish: 'Pagar', vietnamese: 'Thanh toán', phonetic: 'pa-gar', example: 'Pago con tarjeta de crédito.', exampleVi: 'Thanh toán bằng thẻ tín dụng.' },
      { id: 'os4', spanish: 'La devolución', vietnamese: 'Trả hàng', phonetic: 'la đê-bô-lu-xi-ôn', example: 'La devolución es gratuita.', exampleVi: 'Trả hàng miễn phí.' },
      { id: 'os5', spanish: 'El descuento', vietnamese: 'Giảm giá', phonetic: 'eo đết-cuen-tô', example: 'Hay un 20% de descuento.', exampleVi: 'Giảm 20%.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn mua hàng online và cần giúp đỡ.', vietnamese: '' },
      { role: 'ai', spanish: 'Servicio al cliente, ¿en qué puedo ayudarle?', vietnamese: 'Dịch vụ khách hàng, tôi giúp gì được?', tip: '💡 "Servicio al cliente" = Dịch vụ khách hàng. Câu mở đầu phổ biến.' },
      { role: 'user', spanish: 'Quiero devolver un producto. No me queda bien.', vietnamese: 'Tôi muốn trả hàng. Không vừa.' },
      { role: 'ai', spanish: '¿Tiene el número de pedido? La devolución es gratuita en 30 días.', vietnamese: 'Bạn có mã đơn hàng không? Trả hàng miễn phí trong 30 ngày.', suggestions: ['Sí, el número es ABC-12345.', '¿Cómo envío el paquete de vuelta?', '¿Puedo cambiarlo por otra talla?'] },
    ],
  },
  {
    id: 'video-call',
    category: 'Công nghệ', categoryEmoji: '📱',
    title: 'Gọi video',
    difficulty: 'Dễ', xp: 35,
    culturalTip: '🇪🇸 "¡No te oigo!" (Tôi không nghe thấy!) và "¡Se ha congelado!" (Bị đơ rồi!) là hai câu bạn sẽ nghe rất nhiều trong video call!',
    vocabulary: [
      { id: 'vc1', spanish: 'La videollamada', vietnamese: 'Cuộc gọi video', phonetic: 'la bi-đê-ô-gia-ma-đa', example: 'Hacemos una videollamada.', exampleVi: 'Mình gọi video nhé.' },
      { id: 'vc2', spanish: '¿Me oyes?', vietnamese: 'Nghe tôi không?', phonetic: 'mê ô-iêt', example: '¿Me oyes bien?', exampleVi: 'Nghe rõ không?' },
      { id: 'vc3', spanish: 'No te oigo', vietnamese: 'Tôi không nghe thấy', phonetic: 'nô tê ôi-gô', example: '¡No te oigo! ¿Puedes hablar más alto?', exampleVi: 'Tôi không nghe! Nói to hơn được không?' },
      { id: 'vc4', spanish: 'Se ha congelado', vietnamese: 'Bị đơ/lag rồi', phonetic: 'xê a con-hê-la-đô', example: 'La pantalla se ha congelado.', exampleVi: 'Màn hình bị đơ rồi.' },
      { id: 'vc5', spanish: 'Compartir pantalla', vietnamese: 'Chia sẻ màn hình', phonetic: 'com-par-tir pan-ta-gia', example: 'Voy a compartir pantalla.', exampleVi: 'Tôi chia sẻ màn hình nhé.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn gọi video cho bạn TBN.', vietnamese: '' },
      { role: 'ai', spanish: '¡Hola! ¿Me oyes bien? Espera, no te veo...', vietnamese: 'Chào! Nghe rõ không? Đợi, tôi không thấy bạn...', tip: '💡 "¿Me oyes?" / "¿Me ves?" = Nghe/thấy tôi không? Luôn hỏi đầu tiên trong video call.' },
      { role: 'user', spanish: 'Sí, te oigo. ¿Has activado la cámara?', vietnamese: 'Ừ, nghe rõ. Bạn bật camera chưa?' },
      { role: 'ai', spanish: '¡Ah, ya! Ahora sí. ¿Me ves ahora? ¡Qué bien! ¿Cómo estás?', vietnamese: 'À, rồi! Giờ thấy chưa? Tuyệt! Bạn khỏe không?', suggestions: ['¡Sí, ya te veo! Estoy bien, ¿y tú?', 'La conexión está un poco lenta hoy.', '¡Cuánto tiempo sin vernos!'] },
    ],
  },
  {
    id: 'using-apps',
    category: 'Công nghệ', categoryEmoji: '📱',
    title: 'Sử dụng ứng dụng',
    difficulty: 'Trung bình', xp: 45,
    culturalTip: '🇪🇸 App phổ biến ở TBN: Glovo (giao đồ), Bizum (chuyển tiền), Google Maps, Cabify/FreeNow (taxi).',
    vocabulary: [
      { id: 'ua1', spanish: 'Descargar', vietnamese: 'Tải xuống', phonetic: 'đết-car-gar', example: 'Descarga esta aplicación.', exampleVi: 'Tải app này đi.' },
      { id: 'ua2', spanish: 'La contraseña', vietnamese: 'Mật khẩu', phonetic: 'la con-tra-xê-nha', example: 'He olvidado mi contraseña.', exampleVi: 'Tôi quên mật khẩu.' },
      { id: 'ua3', spanish: 'Actualizar', vietnamese: 'Cập nhật', phonetic: 'ac-tu-a-li-xar', example: 'Tienes que actualizar la app.', exampleVi: 'Bạn phải cập nhật app.' },
      { id: 'ua4', spanish: 'No funciona', vietnamese: 'Không hoạt động', phonetic: 'nô phun-xi-ô-na', example: 'La app no funciona.', exampleVi: 'App không hoạt động.' },
      { id: 'ua5', spanish: 'Iniciar sesión', vietnamese: 'Đăng nhập', phonetic: 'i-ni-xi-ar xê-xi-ôn', example: 'Inicia sesión con tu email.', exampleVi: 'Đăng nhập bằng email.' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn nhờ bạn TBN giúp dùng app Bizum.', vietnamese: '' },
      { role: 'ai', spanish: '¿Usas Bizum? Es una app para enviar dinero. Todos la usamos aquí.', vietnamese: 'Bạn dùng Bizum không? Là app chuyển tiền. Ai cũng dùng ở đây.', tip: '💡 Bizum rất phổ biến ở TBN để chia tiền ăn, mua đồ, chuyển tiền bạn bè.' },
      { role: 'user', spanish: 'No, ¿cómo la descargo?', vietnamese: 'Chưa, tải thế nào?' },
      { role: 'ai', spanish: 'Es fácil. Descárgala en la tienda de apps. Después, inicia sesión con tu número de teléfono.', vietnamese: 'Dễ lắm. Tải ở store. Rồi đăng nhập bằng số điện thoại.', suggestions: ['¿Es gratis?', '¿Es segura para enviar dinero?', '¿Puedo usarla con mi banco vietnamita?'] },
    ],
  },
  {
    id: 'tech-support',
    category: 'Công nghệ', categoryEmoji: '📱',
    title: 'Hỗ trợ kỹ thuật',
    difficulty: 'Khó', xp: 60,
    culturalTip: '🇪🇸 Khi gọi hỗ trợ kỹ thuật, nhấn "2" cho TBN. Có thể đợi lâu! "Espere, por favor" = Xin đợi. Chuẩn bị số hợp đồng trước.',
    vocabulary: [
      { id: 'ts1', spanish: 'El problema técnico', vietnamese: 'Sự cố kỹ thuật', phonetic: 'eo prô-blê-ma tếc-ni-cô', example: 'Tengo un problema técnico.', exampleVi: 'Tôi có sự cố kỹ thuật.' },
      { id: 'ts2', spanish: 'Reiniciar', vietnamese: 'Khởi động lại', phonetic: 'rê-i-ni-xi-ar', example: '¿Ha intentado reiniciar?', exampleVi: 'Bạn đã thử khởi động lại chưa?' },
      { id: 'ts3', spanish: 'La conexión a internet', vietnamese: 'Kết nối internet', phonetic: 'la cô-nếc-xi-ôn a in-ter-net', example: 'La conexión a internet no funciona.', exampleVi: 'Internet không hoạt động.' },
      { id: 'ts4', spanish: 'El router', vietnamese: 'Bộ phát wifi', phonetic: 'eo ru-ter', example: 'Apague y encienda el router.', exampleVi: 'Tắt rồi bật lại router.' },
      { id: 'ts5', spanish: 'El número de cliente', vietnamese: 'Mã khách hàng', phonetic: 'eo nu-mê-rô đê cli-en-tê', example: '¿Me dice su número de cliente?', exampleVi: 'Cho tôi mã khách hàng?' },
    ],
    conversation: [
      { role: 'system', spanish: 'Bạn gọi điện hỗ trợ kỹ thuật vì internet không hoạt động.', vietnamese: '' },
      { role: 'ai', spanish: 'Soporte técnico, ¿en qué puedo ayudarle? ¿Me dice su número de cliente?', vietnamese: 'Hỗ trợ kỹ thuật, tôi giúp gì? Cho tôi mã khách hàng?', tip: '💡 Luôn chuẩn bị số hợp đồng/mã khách hàng trước khi gọi hỗ trợ!' },
      { role: 'user', spanish: 'Mi número es 12345. La conexión a internet no funciona desde esta mañana.', vietnamese: 'Mã của tôi là 12345. Internet không hoạt động từ sáng nay.' },
      { role: 'ai', spanish: '¿Ha intentado apagar y encender el router? A veces eso soluciona el problema.', vietnamese: 'Bạn đã thử tắt bật router chưa? Đôi khi điều đó giải quyết được.', suggestions: ['Sí, ya lo he intentado y no funciona.', '¿Cuánto tardará en arreglarse?', '¿Pueden enviar un técnico a mi casa?'] },
    ],
  },
];
