export interface FlashcardWord {
  id: string;
  spanish: string;
  vietnamese: string;
  phonetic: string;
  emoji: string;
  example: string;
  exampleVi: string;
}

export interface FlashcardCategory {
  name: string;
  emoji: string;
  color: string; // tailwind color class for the ring
  words: FlashcardWord[];
}

const objects: FlashcardWord[] = [
  { id: 'ob1', spanish: 'casa', vietnamese: 'nhà', phonetic: 'ca-xa', emoji: '🏠', example: 'Mi casa es grande.', exampleVi: 'Nhà tôi rất lớn.' },
  { id: 'ob2', spanish: 'mesa', vietnamese: 'bàn', phonetic: 'me-xa', emoji: '🪑', example: 'La mesa está limpia.', exampleVi: 'Cái bàn sạch sẽ.' },
  { id: 'ob3', spanish: 'silla', vietnamese: 'ghế', phonetic: 'xi-gia', emoji: '💺', example: 'Siéntate en la silla.', exampleVi: 'Ngồi xuống ghế đi.' },
  { id: 'ob4', spanish: 'cama', vietnamese: 'giường', phonetic: 'ca-ma', emoji: '🛏️', example: 'La cama es cómoda.', exampleVi: 'Giường thoải mái.' },
  { id: 'ob5', spanish: 'puerta', vietnamese: 'cửa', phonetic: 'pu-éc-ta', emoji: '🚪', example: 'Cierra la puerta.', exampleVi: 'Đóng cửa lại.' },
  { id: 'ob6', spanish: 'ventana', vietnamese: 'cửa sổ', phonetic: 'ben-ta-na', emoji: '🪟', example: 'Abre la ventana.', exampleVi: 'Mở cửa sổ ra.' },
  { id: 'ob7', spanish: 'cocina', vietnamese: 'bếp', phonetic: 'cô-xi-na', emoji: '🍳', example: 'La cocina está limpia.', exampleVi: 'Bếp sạch sẽ.' },
  { id: 'ob8', spanish: 'baño', vietnamese: 'phòng tắm', phonetic: 'ba-nhô', emoji: '🚿', example: '¿Dónde está el baño?', exampleVi: 'Phòng tắm ở đâu?' },
  { id: 'ob9', spanish: 'libro', vietnamese: 'sách', phonetic: 'li-brô', emoji: '📖', example: 'Leo un libro.', exampleVi: 'Tôi đọc một cuốn sách.' },
  { id: 'ob10', spanish: 'llave', vietnamese: 'chìa khóa', phonetic: 'gia-bê', emoji: '🔑', example: '¿Dónde está la llave?', exampleVi: 'Chìa khóa ở đâu?' },
  { id: 'ob11', spanish: 'reloj', vietnamese: 'đồng hồ', phonetic: 'rê-lôh', emoji: '⏰', example: 'El reloj marca las tres.', exampleVi: 'Đồng hồ chỉ 3 giờ.' },
  { id: 'ob12', spanish: 'teléfono', vietnamese: 'điện thoại', phonetic: 'tê-lé-phô-nô', emoji: '📱', example: 'Mi teléfono es nuevo.', exampleVi: 'Điện thoại tôi mới.' },
  { id: 'ob13', spanish: 'coche', vietnamese: 'xe hơi', phonetic: 'cô-chê', emoji: '🚗', example: 'El coche es rojo.', exampleVi: 'Xe hơi màu đỏ.' },
  { id: 'ob14', spanish: 'lámpara', vietnamese: 'đèn', phonetic: 'lam-pa-ra', emoji: '💡', example: 'Enciende la lámpara.', exampleVi: 'Bật đèn lên.' },
  { id: 'ob15', spanish: 'espejo', vietnamese: 'gương', phonetic: 'ét-pê-hô', emoji: '🪞', example: 'Mírate en el espejo.', exampleVi: 'Soi gương đi.' },
  { id: 'ob16', spanish: 'televisor', vietnamese: 'tivi', phonetic: 'tê-lê-bi-xor', emoji: '📺', example: 'El televisor está encendido.', exampleVi: 'Tivi đang bật.' },
  { id: 'ob17', spanish: 'ordenador', vietnamese: 'máy tính', phonetic: 'or-đê-na-đor', emoji: '💻', example: 'Trabajo con el ordenador.', exampleVi: 'Tôi làm việc bằng máy tính.' },
  { id: 'ob18', spanish: 'nevera', vietnamese: 'tủ lạnh', phonetic: 'nê-bê-ra', emoji: '🧊', example: 'La leche está en la nevera.', exampleVi: 'Sữa ở trong tủ lạnh.' },
  { id: 'ob19', spanish: 'sofá', vietnamese: 'ghế sofa', phonetic: 'xô-pha', emoji: '🛋️', example: 'Siéntate en el sofá.', exampleVi: 'Ngồi lên sofa đi.' },
  { id: 'ob20', spanish: 'armario', vietnamese: 'tủ quần áo', phonetic: 'ar-ma-ri-ô', emoji: '🗄️', example: 'La ropa está en el armario.', exampleVi: 'Quần áo ở trong tủ.' },
  { id: 'ob21', spanish: 'alfombra', vietnamese: 'thảm', phonetic: 'al-phom-bra', emoji: '🟫', example: 'La alfombra es suave.', exampleVi: 'Tấm thảm mềm.' },
  { id: 'ob22', spanish: 'cuadro', vietnamese: 'bức tranh', phonetic: 'cua-đrô', emoji: '🖼️', example: 'El cuadro es bonito.', exampleVi: 'Bức tranh đẹp.' },
  { id: 'ob23', spanish: 'escalera', vietnamese: 'cầu thang', phonetic: 'ét-ca-lê-ra', emoji: '🪜', example: 'Sube las escaleras.', exampleVi: 'Leo cầu thang lên.' },
  { id: 'ob24', spanish: 'jardín', vietnamese: 'vườn', phonetic: 'har-đin', emoji: '🌿', example: 'El jardín tiene flores.', exampleVi: 'Vườn có hoa.' },
  { id: 'ob25', spanish: 'garaje', vietnamese: 'nhà xe', phonetic: 'ga-ra-hê', emoji: '🏗️', example: 'El coche está en el garaje.', exampleVi: 'Xe ở trong nhà xe.' },
  { id: 'ob26', spanish: 'paraguas', vietnamese: 'dù / ô', phonetic: 'pa-ra-guát', emoji: '☂️', example: 'Lleva un paraguas.', exampleVi: 'Mang theo dù đi.' },
  { id: 'ob27', spanish: 'gafas', vietnamese: 'kính mắt', phonetic: 'ga-phát', emoji: '👓', example: 'Necesito mis gafas.', exampleVi: 'Tôi cần kính mắt.' },
  { id: 'ob28', spanish: 'bolso', vietnamese: 'túi xách', phonetic: 'bol-xô', emoji: '👜', example: 'Mi bolso es negro.', exampleVi: 'Túi xách tôi màu đen.' },
  { id: 'ob29', spanish: 'zapatos', vietnamese: 'giày', phonetic: 'xa-pa-tốt', emoji: '👟', example: 'Ponte los zapatos.', exampleVi: 'Mang giày vào.' },
  { id: 'ob30', spanish: 'toalla', vietnamese: 'khăn tắm', phonetic: 'tô-a-gia', emoji: '🧴', example: 'Dame una toalla.', exampleVi: 'Cho tôi khăn tắm.' },
];

const verbs: FlashcardWord[] = [
  { id: 'vb1', spanish: 'comer', vietnamese: 'ăn', phonetic: 'cô-mer', emoji: '🍽️', example: 'Vamos a comer.', exampleVi: 'Chúng ta đi ăn.' },
  { id: 'vb2', spanish: 'beber', vietnamese: 'uống', phonetic: 'bê-ber', emoji: '🥤', example: '¿Quieres beber algo?', exampleVi: 'Bạn muốn uống gì không?' },
  { id: 'vb3', spanish: 'hablar', vietnamese: 'nói', phonetic: 'a-blar', emoji: '💬', example: 'Hablo español.', exampleVi: 'Tôi nói tiếng TBN.' },
  { id: 'vb4', spanish: 'trabajar', vietnamese: 'làm việc', phonetic: 'tra-ba-har', emoji: '💼', example: 'Trabajo mucho.', exampleVi: 'Tôi làm việc nhiều.' },
  { id: 'vb5', spanish: 'dormir', vietnamese: 'ngủ', phonetic: 'đor-mir', emoji: '😴', example: 'Necesito dormir.', exampleVi: 'Tôi cần ngủ.' },
  { id: 'vb6', spanish: 'leer', vietnamese: 'đọc', phonetic: 'lê-er', emoji: '📚', example: 'Me gusta leer.', exampleVi: 'Tôi thích đọc.' },
  { id: 'vb7', spanish: 'escribir', vietnamese: 'viết', phonetic: 'ét-cri-bir', emoji: '✍️', example: 'Escribo una carta.', exampleVi: 'Tôi viết thư.' },
  { id: 'vb8', spanish: 'correr', vietnamese: 'chạy', phonetic: 'cô-rrer', emoji: '🏃', example: 'Corro por la mañana.', exampleVi: 'Tôi chạy buổi sáng.' },
  { id: 'vb9', spanish: 'cocinar', vietnamese: 'nấu ăn', phonetic: 'cô-xi-nar', emoji: '👨‍🍳', example: 'Me encanta cocinar.', exampleVi: 'Tôi thích nấu ăn.' },
  { id: 'vb10', spanish: 'caminar', vietnamese: 'đi bộ', phonetic: 'ca-mi-nar', emoji: '🚶', example: 'Camino al trabajo.', exampleVi: 'Tôi đi bộ đến chỗ làm.' },
  { id: 'vb11', spanish: 'jugar', vietnamese: 'chơi', phonetic: 'hu-gar', emoji: '🎮', example: 'Los niños juegan.', exampleVi: 'Bọn trẻ đang chơi.' },
  { id: 'vb12', spanish: 'comprar', vietnamese: 'mua', phonetic: 'com-prar', emoji: '🛒', example: 'Voy a comprar pan.', exampleVi: 'Tôi đi mua bánh mì.' },
  { id: 'vb13', spanish: 'vender', vietnamese: 'bán', phonetic: 'ben-đer', emoji: '🏪', example: 'Venden fruta fresca.', exampleVi: 'Họ bán trái cây tươi.' },
  { id: 'vb14', spanish: 'aprender', vietnamese: 'học', phonetic: 'a-pren-đer', emoji: '🎓', example: 'Aprendo español.', exampleVi: 'Tôi học tiếng TBN.' },
  { id: 'vb15', spanish: 'enseñar', vietnamese: 'dạy', phonetic: 'en-xê-nhar', emoji: '👨‍🏫', example: 'Ella enseña matemáticas.', exampleVi: 'Cô ấy dạy toán.' },
  { id: 'vb16', spanish: 'vivir', vietnamese: 'sống', phonetic: 'bi-bir', emoji: '🏡', example: 'Vivo en Madrid.', exampleVi: 'Tôi sống ở Madrid.' },
  { id: 'vb17', spanish: 'abrir', vietnamese: 'mở', phonetic: 'a-brir', emoji: '🔓', example: 'Abre la puerta.', exampleVi: 'Mở cửa ra.' },
  { id: 'vb18', spanish: 'cerrar', vietnamese: 'đóng', phonetic: 'xê-rrar', emoji: '🔒', example: 'Cierra la ventana.', exampleVi: 'Đóng cửa sổ.' },
  { id: 'vb19', spanish: 'cantar', vietnamese: 'hát', phonetic: 'can-tar', emoji: '🎤', example: 'Me gusta cantar.', exampleVi: 'Tôi thích hát.' },
  { id: 'vb20', spanish: 'bailar', vietnamese: 'nhảy / khiêu vũ', phonetic: 'bai-lar', emoji: '💃', example: '¿Quieres bailar?', exampleVi: 'Muốn nhảy không?' },
  { id: 'vb21', spanish: 'nadar', vietnamese: 'bơi', phonetic: 'na-đar', emoji: '🏊', example: 'Nado en la piscina.', exampleVi: 'Tôi bơi ở hồ bơi.' },
  { id: 'vb22', spanish: 'conducir', vietnamese: 'lái xe', phonetic: 'con-đu-xir', emoji: '🚙', example: '¿Sabes conducir?', exampleVi: 'Bạn biết lái xe không?' },
  { id: 'vb23', spanish: 'pagar', vietnamese: 'trả tiền', phonetic: 'pa-gar', emoji: '💳', example: '¿Puedo pagar con tarjeta?', exampleVi: 'Trả bằng thẻ được không?' },
  { id: 'vb24', spanish: 'esperar', vietnamese: 'đợi', phonetic: 'ét-pê-rar', emoji: '⏳', example: 'Espera un momento.', exampleVi: 'Đợi một chút.' },
  { id: 'vb25', spanish: 'llamar', vietnamese: 'gọi', phonetic: 'gia-mar', emoji: '📞', example: 'Te llamo mañana.', exampleVi: 'Ngày mai tôi gọi bạn.' },
  { id: 'vb26', spanish: 'enviar', vietnamese: 'gửi', phonetic: 'en-bi-ar', emoji: '📨', example: 'Envío un mensaje.', exampleVi: 'Tôi gửi tin nhắn.' },
  { id: 'vb27', spanish: 'recibir', vietnamese: 'nhận', phonetic: 'rê-xi-bir', emoji: '📩', example: 'Recibí tu carta.', exampleVi: 'Tôi nhận thư bạn.' },
  { id: 'vb28', spanish: 'pensar', vietnamese: 'nghĩ', phonetic: 'pen-xar', emoji: '💭', example: 'Pienso en ti.', exampleVi: 'Tôi nghĩ về bạn.' },
  { id: 'vb29', spanish: 'creer', vietnamese: 'tin', phonetic: 'crê-er', emoji: '🤞', example: 'Creo que sí.', exampleVi: 'Tôi tin là vậy.' },
  { id: 'vb30', spanish: 'olvidar', vietnamese: 'quên', phonetic: 'ol-bi-đar', emoji: '🫣', example: 'No lo olvides.', exampleVi: 'Đừng quên nhé.' },
];

const time: FlashcardWord[] = [
  { id: 'ti1', spanish: 'lunes', vietnamese: 'thứ Hai', phonetic: 'lu-nét', emoji: '📅', example: 'Hoy es lunes.', exampleVi: 'Hôm nay thứ Hai.' },
  { id: 'ti2', spanish: 'martes', vietnamese: 'thứ Ba', phonetic: 'mar-tét', emoji: '📅', example: 'Martes y jueves.', exampleVi: 'Thứ Ba và thứ Năm.' },
  { id: 'ti3', spanish: 'miércoles', vietnamese: 'thứ Tư', phonetic: 'mi-ér-cô-lét', emoji: '📅', example: 'El miércoles tengo clase.', exampleVi: 'Thứ Tư tôi có lớp.' },
  { id: 'ti4', spanish: 'jueves', vietnamese: 'thứ Năm', phonetic: 'hue-bét', emoji: '📅', example: 'Jueves por la tarde.', exampleVi: 'Chiều thứ Năm.' },
  { id: 'ti5', spanish: 'viernes', vietnamese: 'thứ Sáu', phonetic: 'bi-ér-nét', emoji: '🎉', example: '¡Por fin es viernes!', exampleVi: 'Cuối cùng cũng thứ Sáu!' },
  { id: 'ti6', spanish: 'sábado', vietnamese: 'thứ Bảy', phonetic: 'xa-ba-đô', emoji: '🌞', example: 'El sábado voy al cine.', exampleVi: 'Thứ Bảy đi xem phim.' },
  { id: 'ti7', spanish: 'domingo', vietnamese: 'Chủ nhật', phonetic: 'đô-min-gô', emoji: '☀️', example: 'Domingo es día de descanso.', exampleVi: 'Chủ nhật nghỉ ngơi.' },
  { id: 'ti8', spanish: 'enero', vietnamese: 'tháng Một', phonetic: 'ê-nê-rô', emoji: '❄️', example: 'Enero es frío.', exampleVi: 'Tháng Một lạnh.' },
  { id: 'ti9', spanish: 'febrero', vietnamese: 'tháng Hai', phonetic: 'phê-brê-rô', emoji: '💕', example: 'Febrero tiene 28 días.', exampleVi: 'Tháng Hai có 28 ngày.' },
  { id: 'ti10', spanish: 'marzo', vietnamese: 'tháng Ba', phonetic: 'mar-xô', emoji: '🌸', example: 'En marzo hace buen tiempo.', exampleVi: 'Tháng Ba thời tiết đẹp.' },
  { id: 'ti11', spanish: 'mañana', vietnamese: 'buổi sáng / ngày mai', phonetic: 'ma-nha-na', emoji: '🌅', example: 'Hasta mañana.', exampleVi: 'Hẹn ngày mai.' },
  { id: 'ti12', spanish: 'tarde', vietnamese: 'buổi chiều', phonetic: 'tar-đê', emoji: '🌇', example: 'Buenas tardes.', exampleVi: 'Chào buổi chiều.' },
  { id: 'ti13', spanish: 'noche', vietnamese: 'buổi tối / đêm', phonetic: 'nô-chê', emoji: '🌙', example: 'Buenas noches.', exampleVi: 'Chúc ngủ ngon.' },
  { id: 'ti14', spanish: 'hoy', vietnamese: 'hôm nay', phonetic: 'oi', emoji: '📌', example: 'Hoy es un buen día.', exampleVi: 'Hôm nay là ngày đẹp.' },
  { id: 'ti15', spanish: 'ayer', vietnamese: 'hôm qua', phonetic: 'a-giêr', emoji: '⏪', example: 'Ayer fue genial.', exampleVi: 'Hôm qua tuyệt.' },
  { id: 'ti16', spanish: 'semana', vietnamese: 'tuần', phonetic: 'xê-ma-na', emoji: '📆', example: 'La próxima semana.', exampleVi: 'Tuần sau.' },
  { id: 'ti17', spanish: 'mes', vietnamese: 'tháng', phonetic: 'met', emoji: '🗓️', example: 'El mes que viene.', exampleVi: 'Tháng tới.' },
  { id: 'ti18', spanish: 'año', vietnamese: 'năm', phonetic: 'a-nhô', emoji: '🎆', example: '¡Feliz Año Nuevo!', exampleVi: 'Chúc mừng năm mới!' },
  { id: 'ti19', spanish: 'hora', vietnamese: 'giờ', phonetic: 'ô-ra', emoji: '🕐', example: '¿Qué hora es?', exampleVi: 'Mấy giờ rồi?' },
  { id: 'ti20', spanish: 'minuto', vietnamese: 'phút', phonetic: 'mi-nu-tô', emoji: '⏱️', example: 'Espera un minuto.', exampleVi: 'Đợi một phút.' },
  { id: 'ti21', spanish: 'siempre', vietnamese: 'luôn luôn', phonetic: 'xi-em-prê', emoji: '♾️', example: 'Siempre estoy contigo.', exampleVi: 'Luôn ở bên bạn.' },
  { id: 'ti22', spanish: 'nunca', vietnamese: 'không bao giờ', phonetic: 'nun-ca', emoji: '🚫', example: 'Nunca es tarde.', exampleVi: 'Không bao giờ là muộn.' },
  { id: 'ti23', spanish: 'a veces', vietnamese: 'thỉnh thoảng', phonetic: 'a bê-xêt', emoji: '🔄', example: 'A veces llueve.', exampleVi: 'Thỉnh thoảng mưa.' },
  { id: 'ti24', spanish: 'temprano', vietnamese: 'sớm', phonetic: 'tem-pra-nô', emoji: '🌄', example: 'Me levanto temprano.', exampleVi: 'Tôi dậy sớm.' },
  { id: 'ti25', spanish: 'tarde', vietnamese: 'trễ', phonetic: 'tar-đê', emoji: '🐌', example: 'Llegas tarde.', exampleVi: 'Bạn đến trễ.' },
  { id: 'ti26', spanish: 'primavera', vietnamese: 'mùa xuân', phonetic: 'pri-ma-bê-ra', emoji: '🌷', example: 'Me gusta la primavera.', exampleVi: 'Tôi thích mùa xuân.' },
  { id: 'ti27', spanish: 'verano', vietnamese: 'mùa hè', phonetic: 'bê-ra-nô', emoji: '☀️', example: 'En verano hace calor.', exampleVi: 'Mùa hè nóng.' },
  { id: 'ti28', spanish: 'otoño', vietnamese: 'mùa thu', phonetic: 'ô-tô-nhô', emoji: '🍂', example: 'El otoño es bonito.', exampleVi: 'Mùa thu đẹp.' },
  { id: 'ti29', spanish: 'invierno', vietnamese: 'mùa đông', phonetic: 'in-bi-ér-nô', emoji: '❄️', example: 'El invierno es frío.', exampleVi: 'Mùa đông lạnh.' },
  { id: 'ti30', spanish: 'cumpleaños', vietnamese: 'sinh nhật', phonetic: 'cum-plê-a-nhốt', emoji: '🎂', example: '¡Feliz cumpleaños!', exampleVi: 'Chúc mừng sinh nhật!' },
];

const people: FlashcardWord[] = [
  { id: 'pe1', spanish: 'familia', vietnamese: 'gia đình', phonetic: 'pha-mi-lia', emoji: '👨‍👩‍👧‍👦', example: 'Mi familia es grande.', exampleVi: 'Gia đình tôi đông.' },
  { id: 'pe2', spanish: 'amigo', vietnamese: 'bạn', phonetic: 'a-mi-gô', emoji: '🤝', example: 'Él es mi amigo.', exampleVi: 'Anh ấy là bạn tôi.' },
  { id: 'pe3', spanish: 'madre', vietnamese: 'mẹ', phonetic: 'ma-đrê', emoji: '👩', example: 'Mi madre cocina bien.', exampleVi: 'Mẹ tôi nấu ăn ngon.' },
  { id: 'pe4', spanish: 'padre', vietnamese: 'bố', phonetic: 'pa-đrê', emoji: '👨', example: 'Mi padre trabaja.', exampleVi: 'Bố tôi đi làm.' },
  { id: 'pe5', spanish: 'hijo', vietnamese: 'con trai', phonetic: 'i-hô', emoji: '👦', example: 'Mi hijo tiene cinco años.', exampleVi: 'Con trai tôi 5 tuổi.' },
  { id: 'pe6', spanish: 'hija', vietnamese: 'con gái', phonetic: 'i-ha', emoji: '👧', example: 'Mi hija es inteligente.', exampleVi: 'Con gái tôi thông minh.' },
  { id: 'pe7', spanish: 'hermano', vietnamese: 'anh/em trai', phonetic: 'er-ma-nô', emoji: '👬', example: 'Tengo dos hermanos.', exampleVi: 'Tôi có 2 anh em trai.' },
  { id: 'pe8', spanish: 'hermana', vietnamese: 'chị/em gái', phonetic: 'er-ma-na', emoji: '👭', example: 'Mi hermana vive en Barcelona.', exampleVi: 'Chị tôi sống ở Barcelona.' },
  { id: 'pe9', spanish: 'abuelo', vietnamese: 'ông', phonetic: 'a-bue-lô', emoji: '👴', example: 'Mi abuelo tiene 80 años.', exampleVi: 'Ông tôi 80 tuổi.' },
  { id: 'pe10', spanish: 'abuela', vietnamese: 'bà', phonetic: 'a-bue-la', emoji: '👵', example: 'Mi abuela cocina muy bien.', exampleVi: 'Bà tôi nấu ăn rất ngon.' },
  { id: 'pe11', spanish: 'vecino', vietnamese: 'hàng xóm', phonetic: 'bê-xi-nô', emoji: '🏘️', example: 'Mi vecino es amable.', exampleVi: 'Hàng xóm tôi thân thiện.' },
  { id: 'pe12', spanish: 'médico', vietnamese: 'bác sĩ', phonetic: 'mé-đi-cô', emoji: '👨‍⚕️', example: 'El médico me ayudó.', exampleVi: 'Bác sĩ đã giúp tôi.' },
  { id: 'pe13', spanish: 'profesor', vietnamese: 'giáo viên', phonetic: 'prô-phê-xor', emoji: '👨‍🏫', example: 'El profesor explica bien.', exampleVi: 'Giáo viên giảng hay.' },
  { id: 'pe14', spanish: 'niño', vietnamese: 'trẻ em', phonetic: 'ni-nhô', emoji: '👶', example: 'El niño juega.', exampleVi: 'Đứa trẻ đang chơi.' },
  { id: 'pe15', spanish: 'mujer', vietnamese: 'phụ nữ / vợ', phonetic: 'mu-her', emoji: '👩', example: 'La mujer trabaja.', exampleVi: 'Người phụ nữ làm việc.' },
  { id: 'pe16', spanish: 'hombre', vietnamese: 'đàn ông / chồng', phonetic: 'om-brê', emoji: '👨', example: 'El hombre es alto.', exampleVi: 'Người đàn ông cao.' },
  { id: 'pe17', spanish: 'novio', vietnamese: 'bạn trai', phonetic: 'nô-bi-ô', emoji: '💑', example: 'Mi novio es simpático.', exampleVi: 'Bạn trai tôi dễ thương.' },
  { id: 'pe18', spanish: 'novia', vietnamese: 'bạn gái', phonetic: 'nô-bi-a', emoji: '💏', example: 'Mi novia cocina bien.', exampleVi: 'Bạn gái tôi nấu ăn ngon.' },
  { id: 'pe19', spanish: 'tío', vietnamese: 'chú / bác', phonetic: 'ti-ô', emoji: '👨‍🦱', example: 'Mi tío vive en Sevilla.', exampleVi: 'Chú tôi sống ở Sevilla.' },
  { id: 'pe20', spanish: 'tía', vietnamese: 'cô / dì', phonetic: 'ti-a', emoji: '👩‍🦱', example: 'Mi tía es doctora.', exampleVi: 'Dì tôi là bác sĩ.' },
  { id: 'pe21', spanish: 'primo', vietnamese: 'anh/em họ', phonetic: 'pri-mô', emoji: '👦', example: 'Mi primo tiene 15 años.', exampleVi: 'Em họ tôi 15 tuổi.' },
  { id: 'pe22', spanish: 'sobrino', vietnamese: 'cháu trai', phonetic: 'xô-bri-nô', emoji: '🧒', example: 'Mi sobrino es divertido.', exampleVi: 'Cháu trai tôi vui tính.' },
  { id: 'pe23', spanish: 'jefe', vietnamese: 'sếp', phonetic: 'hê-phê', emoji: '👔', example: 'Mi jefe es amable.', exampleVi: 'Sếp tôi tốt bụng.' },
  { id: 'pe24', spanish: 'compañero', vietnamese: 'đồng nghiệp', phonetic: 'com-pa-nhê-rô', emoji: '🤝', example: 'Mi compañero me ayuda.', exampleVi: 'Đồng nghiệp giúp tôi.' },
  { id: 'pe25', spanish: 'bebé', vietnamese: 'em bé', phonetic: 'bê-bé', emoji: '👶', example: 'El bebé duerme.', exampleVi: 'Em bé đang ngủ.' },
  { id: 'pe26', spanish: 'persona', vietnamese: 'người', phonetic: 'per-xô-na', emoji: '🧑', example: 'Es una buena persona.', exampleVi: 'Là người tốt.' },
  { id: 'pe27', spanish: 'gente', vietnamese: 'mọi người', phonetic: 'hen-tê', emoji: '👥', example: 'Hay mucha gente.', exampleVi: 'Rất đông người.' },
  { id: 'pe28', spanish: 'marido', vietnamese: 'chồng', phonetic: 'ma-ri-đô', emoji: '💍', example: 'Mi marido cocina.', exampleVi: 'Chồng tôi nấu ăn.' },
  { id: 'pe29', spanish: 'esposa', vietnamese: 'vợ', phonetic: 'ét-pô-xa', emoji: '💍', example: 'Mi esposa trabaja.', exampleVi: 'Vợ tôi đi làm.' },
  { id: 'pe30', spanish: 'suegra', vietnamese: 'mẹ chồng/vợ', phonetic: 'xue-gra', emoji: '👩‍🦳', example: 'Mi suegra cocina bien.', exampleVi: 'Mẹ chồng nấu ăn ngon.' },
];

const food: FlashcardWord[] = [
  { id: 'fo1', spanish: 'pan', vietnamese: 'bánh mì', phonetic: 'pan', emoji: '🍞', example: 'Quiero pan.', exampleVi: 'Tôi muốn bánh mì.' },
  { id: 'fo2', spanish: 'agua', vietnamese: 'nước', phonetic: 'a-gua', emoji: '💧', example: 'Dame agua.', exampleVi: 'Cho tôi nước.' },
  { id: 'fo3', spanish: 'café', vietnamese: 'cà phê', phonetic: 'ca-phê', emoji: '☕', example: 'Un café con leche.', exampleVi: 'Cà phê sữa.' },
  { id: 'fo4', spanish: 'arroz', vietnamese: 'cơm / gạo', phonetic: 'a-rrốt', emoji: '🍚', example: 'Como arroz todos los días.', exampleVi: 'Tôi ăn cơm mỗi ngày.' },
  { id: 'fo5', spanish: 'pollo', vietnamese: 'gà', phonetic: 'pô-giô', emoji: '🍗', example: 'El pollo está rico.', exampleVi: 'Gà ngon lắm.' },
  { id: 'fo6', spanish: 'fruta', vietnamese: 'trái cây', phonetic: 'phru-ta', emoji: '🍎', example: 'Me gustan las frutas.', exampleVi: 'Tôi thích trái cây.' },
  { id: 'fo7', spanish: 'queso', vietnamese: 'phô mai', phonetic: 'kê-xô', emoji: '🧀', example: 'El queso manchego.', exampleVi: 'Phô mai manchego.' },
  { id: 'fo8', spanish: 'vino', vietnamese: 'rượu vang', phonetic: 'bi-nô', emoji: '🍷', example: 'Un vino tinto, por favor.', exampleVi: 'Một ly vang đỏ.' },
  { id: 'fo9', spanish: 'leche', vietnamese: 'sữa', phonetic: 'lê-chê', emoji: '🥛', example: 'Bebo leche.', exampleVi: 'Tôi uống sữa.' },
  { id: 'fo10', spanish: 'huevo', vietnamese: 'trứng', phonetic: 'ue-bô', emoji: '🥚', example: 'Un huevo frito.', exampleVi: 'Một quả trứng chiên.' },
  { id: 'fo11', spanish: 'pescado', vietnamese: 'cá', phonetic: 'pết-ca-đô', emoji: '🐟', example: 'El pescado está fresco.', exampleVi: 'Cá rất tươi.' },
  { id: 'fo12', spanish: 'carne', vietnamese: 'thịt', phonetic: 'car-nê', emoji: '🥩', example: 'La carne está deliciosa.', exampleVi: 'Thịt rất ngon.' },
  { id: 'fo13', spanish: 'verdura', vietnamese: 'rau', phonetic: 'ber-đu-ra', emoji: '🥬', example: 'Come más verduras.', exampleVi: 'Ăn nhiều rau hơn.' },
  { id: 'fo14', spanish: 'tomate', vietnamese: 'cà chua', phonetic: 'tô-ma-tê', emoji: '🍅', example: 'El tomate es rojo.', exampleVi: 'Cà chua màu đỏ.' },
  { id: 'fo15', spanish: 'patata', vietnamese: 'khoai tây', phonetic: 'pa-ta-ta', emoji: '🥔', example: 'Patatas fritas.', exampleVi: 'Khoai tây chiên.' },
  { id: 'fo16', spanish: 'cerveza', vietnamese: 'bia', phonetic: 'xer-bê-xa', emoji: '🍺', example: 'Una cerveza, por favor.', exampleVi: 'Một ly bia.' },
  { id: 'fo17', spanish: 'ensalada', vietnamese: 'salad', phonetic: 'en-xa-la-đa', emoji: '🥗', example: 'Una ensalada mixta.', exampleVi: 'Một salad thập cẩm.' },
  { id: 'fo18', spanish: 'sopa', vietnamese: 'súp', phonetic: 'xô-pa', emoji: '🍲', example: 'La sopa está caliente.', exampleVi: 'Súp nóng.' },
  { id: 'fo19', spanish: 'azúcar', vietnamese: 'đường', phonetic: 'a-xu-car', emoji: '🍬', example: '¿Con azúcar?', exampleVi: 'Có đường không?' },
  { id: 'fo20', spanish: 'sal', vietnamese: 'muối', phonetic: 'xal', emoji: '🧂', example: 'Pásame la sal.', exampleVi: 'Đưa muối đây.' },
  { id: 'fo21', spanish: 'aceite', vietnamese: 'dầu', phonetic: 'a-xei-tê', emoji: '🫒', example: 'Aceite de oliva.', exampleVi: 'Dầu ô liu.' },
  { id: 'fo22', spanish: 'helado', vietnamese: 'kem', phonetic: 'ê-la-đô', emoji: '🍦', example: 'Quiero un helado.', exampleVi: 'Tôi muốn kem.' },
  { id: 'fo23', spanish: 'tarta', vietnamese: 'bánh kem', phonetic: 'tar-ta', emoji: '🎂', example: 'La tarta de chocolate.', exampleVi: 'Bánh kem sô-cô-la.' },
  { id: 'fo24', spanish: 'zumo', vietnamese: 'nước ép', phonetic: 'xu-mô', emoji: '🧃', example: 'Un zumo de naranja.', exampleVi: 'Nước cam ép.' },
  { id: 'fo25', spanish: 'naranja', vietnamese: 'cam', phonetic: 'na-ran-ha', emoji: '🍊', example: 'La naranja es dulce.', exampleVi: 'Cam ngọt.' },
  { id: 'fo26', spanish: 'manzana', vietnamese: 'táo', phonetic: 'man-xa-na', emoji: '🍏', example: 'Come una manzana.', exampleVi: 'Ăn một quả táo.' },
  { id: 'fo27', spanish: 'plátano', vietnamese: 'chuối', phonetic: 'pla-ta-nô', emoji: '🍌', example: 'El plátano es amarillo.', exampleVi: 'Chuối màu vàng.' },
  { id: 'fo28', spanish: 'gambas', vietnamese: 'tôm', phonetic: 'gam-bát', emoji: '🦐', example: 'Gambas al ajillo.', exampleVi: 'Tôm rang tỏi.' },
  { id: 'fo29', spanish: 'jamón', vietnamese: 'giăm-bông', phonetic: 'ha-môn', emoji: '🥓', example: 'Jamón ibérico.', exampleVi: 'Giăm-bông Ibérico.' },
  { id: 'fo30', spanish: 'churros', vietnamese: 'churros (bánh quẩy TBN)', phonetic: 'chu-rrốt', emoji: '🥨', example: 'Churros con chocolate.', exampleVi: 'Churros với sô-cô-la.' },
];

const colors: FlashcardWord[] = [
  { id: 'co1', spanish: 'rojo', vietnamese: 'đỏ', phonetic: 'rô-hô', emoji: '🔴', example: 'El coche es rojo.', exampleVi: 'Xe hơi màu đỏ.' },
  { id: 'co2', spanish: 'azul', vietnamese: 'xanh dương', phonetic: 'a-xul', emoji: '🔵', example: 'El cielo es azul.', exampleVi: 'Bầu trời xanh.' },
  { id: 'co3', spanish: 'verde', vietnamese: 'xanh lá', phonetic: 'ber-đê', emoji: '🟢', example: 'La hierba es verde.', exampleVi: 'Cỏ màu xanh lá.' },
  { id: 'co4', spanish: 'amarillo', vietnamese: 'vàng', phonetic: 'a-ma-ri-giô', emoji: '🟡', example: 'El sol es amarillo.', exampleVi: 'Mặt trời vàng.' },
  { id: 'co5', spanish: 'blanco', vietnamese: 'trắng', phonetic: 'blan-cô', emoji: '⚪', example: 'La nieve es blanca.', exampleVi: 'Tuyết trắng.' },
  { id: 'co6', spanish: 'negro', vietnamese: 'đen', phonetic: 'nê-grô', emoji: '⚫', example: 'El gato es negro.', exampleVi: 'Con mèo đen.' },
  { id: 'co7', spanish: 'naranja', vietnamese: 'cam', phonetic: 'na-ran-ha', emoji: '🟠', example: 'El color naranja.', exampleVi: 'Màu cam.' },
  { id: 'co8', spanish: 'rosa', vietnamese: 'hồng', phonetic: 'rô-xa', emoji: '🩷', example: 'La flor es rosa.', exampleVi: 'Hoa màu hồng.' },
  { id: 'co9', spanish: 'morado', vietnamese: 'tím', phonetic: 'mô-ra-đô', emoji: '🟣', example: 'Me gusta el morado.', exampleVi: 'Tôi thích màu tím.' },
  { id: 'co10', spanish: 'gris', vietnamese: 'xám', phonetic: 'grit', emoji: '🩶', example: 'El cielo está gris.', exampleVi: 'Trời xám.' },
  { id: 'co11', spanish: 'marrón', vietnamese: 'nâu', phonetic: 'ma-rrôn', emoji: '🟤', example: 'Los zapatos son marrones.', exampleVi: 'Giày màu nâu.' },
  { id: 'co12', spanish: 'grande', vietnamese: 'lớn', phonetic: 'gran-đê', emoji: '📐', example: 'La casa es grande.', exampleVi: 'Nhà lớn.' },
  { id: 'co13', spanish: 'pequeño', vietnamese: 'nhỏ', phonetic: 'pê-kê-nhô', emoji: '🔹', example: 'Un perro pequeño.', exampleVi: 'Con chó nhỏ.' },
  { id: 'co14', spanish: 'largo', vietnamese: 'dài', phonetic: 'lar-gô', emoji: '📏', example: 'El río es largo.', exampleVi: 'Con sông dài.' },
  { id: 'co15', spanish: 'corto', vietnamese: 'ngắn', phonetic: 'cor-tô', emoji: '✂️', example: 'El pelo es corto.', exampleVi: 'Tóc ngắn.' },
  { id: 'co16', spanish: 'alto', vietnamese: 'cao', phonetic: 'al-tô', emoji: '📈', example: 'El edificio es alto.', exampleVi: 'Tòa nhà cao.' },
  { id: 'co17', spanish: 'bajo', vietnamese: 'thấp', phonetic: 'ba-hô', emoji: '📉', example: 'Es bajo de estatura.', exampleVi: 'Người thấp.' },
  { id: 'co18', spanish: 'gordo', vietnamese: 'mập', phonetic: 'gor-đô', emoji: '🐷', example: 'El gato es gordo.', exampleVi: 'Con mèo mập.' },
  { id: 'co19', spanish: 'delgado', vietnamese: 'ốm / gầy', phonetic: 'đel-ga-đô', emoji: '🩸', example: 'Ella es delgada.', exampleVi: 'Cô ấy gầy.' },
  { id: 'co20', spanish: 'bonito', vietnamese: 'đẹp', phonetic: 'bô-ni-tô', emoji: '✨', example: '¡Qué bonito!', exampleVi: 'Đẹp quá!' },
  { id: 'co21', spanish: 'feo', vietnamese: 'xấu', phonetic: 'phê-ô', emoji: '👎', example: 'No es feo.', exampleVi: 'Không xấu.' },
  { id: 'co22', spanish: 'nuevo', vietnamese: 'mới', phonetic: 'nue-bô', emoji: '🆕', example: 'Tengo un coche nuevo.', exampleVi: 'Tôi có xe mới.' },
  { id: 'co23', spanish: 'viejo', vietnamese: 'cũ / già', phonetic: 'bi-ê-hô', emoji: '🏚️', example: 'La casa es vieja.', exampleVi: 'Nhà cũ.' },
  { id: 'co24', spanish: 'redondo', vietnamese: 'tròn', phonetic: 'rê-đon-đô', emoji: '⭕', example: 'La mesa es redonda.', exampleVi: 'Bàn tròn.' },
  { id: 'co25', spanish: 'cuadrado', vietnamese: 'vuông', phonetic: 'cua-đra-đô', emoji: '⬜', example: 'La caja es cuadrada.', exampleVi: 'Hộp vuông.' },
  { id: 'co26', spanish: 'ligero', vietnamese: 'nhẹ', phonetic: 'li-hê-rô', emoji: '🪶', example: 'Es muy ligero.', exampleVi: 'Rất nhẹ.' },
  { id: 'co27', spanish: 'pesado', vietnamese: 'nặng', phonetic: 'pê-xa-đô', emoji: '🏋️', example: 'La maleta es pesada.', exampleVi: 'Vali nặng.' },
  { id: 'co28', spanish: 'suave', vietnamese: 'mềm', phonetic: 'xua-bê', emoji: '🧸', example: 'La tela es suave.', exampleVi: 'Vải mềm.' },
  { id: 'co29', spanish: 'duro', vietnamese: 'cứng', phonetic: 'đu-rô', emoji: '🪨', example: 'El pan está duro.', exampleVi: 'Bánh mì cứng.' },
  { id: 'co30', spanish: 'limpio', vietnamese: 'sạch', phonetic: 'lim-pi-ô', emoji: '✨', example: 'La casa está limpia.', exampleVi: 'Nhà sạch.' },
];

const feelings: FlashcardWord[] = [
  { id: 'fe1', spanish: 'feliz', vietnamese: 'hạnh phúc', phonetic: 'phê-lít', emoji: '😊', example: 'Estoy feliz.', exampleVi: 'Tôi hạnh phúc.' },
  { id: 'fe2', spanish: 'triste', vietnamese: 'buồn', phonetic: 'trít-tê', emoji: '😢', example: 'Estoy triste.', exampleVi: 'Tôi buồn.' },
  { id: 'fe3', spanish: 'cansado', vietnamese: 'mệt', phonetic: 'can-xa-đô', emoji: '😫', example: 'Estoy cansado.', exampleVi: 'Tôi mệt.' },
  { id: 'fe4', spanish: 'nervioso', vietnamese: 'lo lắng', phonetic: 'ner-bi-ô-xô', emoji: '😰', example: 'Estoy nervioso.', exampleVi: 'Tôi lo lắng.' },
  { id: 'fe5', spanish: 'tranquilo', vietnamese: 'bình tĩnh', phonetic: 'tran-ki-lô', emoji: '😌', example: 'Estoy tranquilo.', exampleVi: 'Tôi bình tĩnh.' },
  { id: 'fe6', spanish: 'amable', vietnamese: 'tốt bụng', phonetic: 'a-ma-blê', emoji: '🥰', example: 'Eres muy amable.', exampleVi: 'Bạn tốt bụng quá.' },
  { id: 'fe7', spanish: 'enfadado', vietnamese: 'tức giận', phonetic: 'en-pha-đa-đô', emoji: '😠', example: 'No estés enfadado.', exampleVi: 'Đừng tức giận.' },
  { id: 'fe8', spanish: 'sorprendido', vietnamese: 'ngạc nhiên', phonetic: 'xor-pren-đi-đô', emoji: '😲', example: 'Estoy sorprendido.', exampleVi: 'Tôi ngạc nhiên.' },
  { id: 'fe9', spanish: 'emocionado', vietnamese: 'hào hứng', phonetic: 'ê-mô-xiô-na-đô', emoji: '🤩', example: '¡Estoy emocionado!', exampleVi: 'Tôi rất hào hứng!' },
  { id: 'fe10', spanish: 'aburrido', vietnamese: 'chán', phonetic: 'a-bu-rri-đô', emoji: '😑', example: 'Estoy aburrido.', exampleVi: 'Tôi chán.' },
  { id: 'fe11', spanish: 'contento', vietnamese: 'vui vẻ', phonetic: 'con-ten-tô', emoji: '😄', example: 'Estoy contento.', exampleVi: 'Tôi vui vẻ.' },
  { id: 'fe12', spanish: 'preocupado', vietnamese: 'lo lắng', phonetic: 'prê-ô-cu-pa-đô', emoji: '😟', example: 'Estoy preocupado.', exampleVi: 'Tôi lo lắng.' },
  { id: 'fe13', spanish: 'asustado', vietnamese: 'sợ hãi', phonetic: 'a-xút-ta-đô', emoji: '😨', example: 'Estoy asustado.', exampleVi: 'Tôi sợ.' },
  { id: 'fe14', spanish: 'orgulloso', vietnamese: 'tự hào', phonetic: 'or-gu-giô-xô', emoji: '🦁', example: 'Estoy orgulloso de ti.', exampleVi: 'Tôi tự hào về bạn.' },
  { id: 'fe15', spanish: 'avergonzado', vietnamese: 'xấu hổ', phonetic: 'a-ber-gon-xa-đô', emoji: '😳', example: 'Estoy avergonzado.', exampleVi: 'Tôi xấu hổ.' },
  { id: 'fe16', spanish: 'celoso', vietnamese: 'ghen', phonetic: 'xê-lô-xô', emoji: '😒', example: 'No seas celoso.', exampleVi: 'Đừng ghen.' },
  { id: 'fe17', spanish: 'agradecido', vietnamese: 'biết ơn', phonetic: 'a-gra-đê-xi-đô', emoji: '🙏', example: 'Estoy agradecido.', exampleVi: 'Tôi biết ơn.' },
  { id: 'fe18', spanish: 'enamorado', vietnamese: 'yêu / đang yêu', phonetic: 'ê-na-mô-ra-đô', emoji: '😍', example: 'Estoy enamorado.', exampleVi: 'Tôi đang yêu.' },
  { id: 'fe19', spanish: 'solitario', vietnamese: 'cô đơn', phonetic: 'xô-li-ta-ri-ô', emoji: '🥺', example: 'Me siento solitario.', exampleVi: 'Tôi cảm thấy cô đơn.' },
  { id: 'fe20', spanish: 'valiente', vietnamese: 'dũng cảm', phonetic: 'ba-li-en-tê', emoji: '💪', example: '¡Sé valiente!', exampleVi: 'Hãy dũng cảm!' },
  { id: 'fe21', spanish: 'generoso', vietnamese: 'hào phóng', phonetic: 'hê-nê-rô-xô', emoji: '🎁', example: 'Eres muy generoso.', exampleVi: 'Bạn hào phóng quá.' },
  { id: 'fe22', spanish: 'perezoso', vietnamese: 'lười', phonetic: 'pê-rê-xô-xô', emoji: '🦥', example: 'No seas perezoso.', exampleVi: 'Đừng lười.' },
  { id: 'fe23', spanish: 'simpático', vietnamese: 'dễ thương', phonetic: 'xim-pa-ti-cô', emoji: '😊', example: 'Es muy simpático.', exampleVi: 'Rất dễ thương.' },
  { id: 'fe24', spanish: 'antipático', vietnamese: 'khó ưa', phonetic: 'an-ti-pa-ti-cô', emoji: '😤', example: 'Es un poco antipático.', exampleVi: 'Hơi khó ưa.' },
  { id: 'fe25', spanish: 'tímido', vietnamese: 'nhút nhát', phonetic: 'ti-mi-đô', emoji: '🫣', example: 'Es tímido.', exampleVi: 'Nhút nhát.' },
  { id: 'fe26', spanish: 'seguro', vietnamese: 'tự tin', phonetic: 'xê-gu-rô', emoji: '😎', example: 'Estoy seguro.', exampleVi: 'Tôi tự tin.' },
  { id: 'fe27', spanish: 'confundido', vietnamese: 'bối rối', phonetic: 'con-phun-đi-đô', emoji: '🤔', example: 'Estoy confundido.', exampleVi: 'Tôi bối rối.' },
  { id: 'fe28', spanish: 'curioso', vietnamese: 'tò mò', phonetic: 'cu-ri-ô-xô', emoji: '🧐', example: 'Soy curioso.', exampleVi: 'Tôi tò mò.' },
  { id: 'fe29', spanish: 'ilusionado', vietnamese: 'hào hứng / mong đợi', phonetic: 'i-lu-xiô-na-đô', emoji: '🌟', example: 'Estoy ilusionado con el viaje.', exampleVi: 'Tôi mong đợi chuyến đi.' },
  { id: 'fe30', spanish: 'relajado', vietnamese: 'thư giãn', phonetic: 'rê-la-ha-đô', emoji: '🧘', example: 'Estoy relajado.', exampleVi: 'Tôi thư giãn.' },
];

const numbers: FlashcardWord[] = [
  { id: 'nu1', spanish: 'uno', vietnamese: 'một', phonetic: 'u-nô', emoji: '1️⃣', example: 'Tengo uno.', exampleVi: 'Tôi có một.' },
  { id: 'nu2', spanish: 'dos', vietnamese: 'hai', phonetic: 'đốt', emoji: '2️⃣', example: 'Somos dos.', exampleVi: 'Chúng tôi 2 người.' },
  { id: 'nu3', spanish: 'tres', vietnamese: 'ba', phonetic: 'trết', emoji: '3️⃣', example: 'Tres cafés.', exampleVi: 'Ba ly cà phê.' },
  { id: 'nu4', spanish: 'cinco', vietnamese: 'năm', phonetic: 'xin-cô', emoji: '5️⃣', example: 'Son las cinco.', exampleVi: 'Năm giờ.' },
  { id: 'nu5', spanish: 'diez', vietnamese: 'mười', phonetic: 'đi-ết', emoji: '🔟', example: 'Diez euros.', exampleVi: 'Mười euro.' },
  { id: 'nu6', spanish: 'veinte', vietnamese: 'hai mươi', phonetic: 'bein-tê', emoji: '2️⃣0️⃣', example: 'Tengo veinte años.', exampleVi: 'Tôi 20 tuổi.' },
  { id: 'nu7', spanish: 'cien', vietnamese: 'một trăm', phonetic: 'xi-en', emoji: '💯', example: 'Cien euros.', exampleVi: 'Một trăm euro.' },
  { id: 'nu8', spanish: 'mil', vietnamese: 'một ngàn', phonetic: 'mil', emoji: '🔢', example: 'Mil personas.', exampleVi: 'Một ngàn người.' },
  { id: 'nu9', spanish: 'precio', vietnamese: 'giá', phonetic: 'prê-xi-ô', emoji: '💰', example: '¿Cuál es el precio?', exampleVi: 'Giá bao nhiêu?' },
  { id: 'nu10', spanish: 'euro', vietnamese: 'euro', phonetic: 'eu-rô', emoji: '💶', example: 'Cuesta cinco euros.', exampleVi: 'Giá năm euro.' },
  { id: 'nu11', spanish: 'barato', vietnamese: 'rẻ', phonetic: 'ba-ra-tô', emoji: '🏷️', example: 'Es muy barato.', exampleVi: 'Rẻ lắm.' },
  { id: 'nu12', spanish: 'caro', vietnamese: 'đắt', phonetic: 'ca-rô', emoji: '💎', example: 'Es muy caro.', exampleVi: 'Đắt lắm.' },
  { id: 'nu13', spanish: 'pagar', vietnamese: 'trả tiền', phonetic: 'pa-gar', emoji: '💳', example: '¿Puedo pagar con tarjeta?', exampleVi: 'Trả bằng thẻ được không?' },
  { id: 'nu14', spanish: 'dinero', vietnamese: 'tiền', phonetic: 'đi-nê-rô', emoji: '💵', example: 'No tengo dinero.', exampleVi: 'Tôi không có tiền.' },
  { id: 'nu15', spanish: 'cambio', vietnamese: 'tiền thối', phonetic: 'cam-bi-ô', emoji: '🪙', example: '¿Tiene cambio?', exampleVi: 'Có tiền thối không?' },
  { id: 'nu16', spanish: 'cuenta', vietnamese: 'hóa đơn', phonetic: 'cuen-ta', emoji: '🧾', example: 'La cuenta, por favor.', exampleVi: 'Tính tiền.' },
  { id: 'nu17', spanish: 'descuento', vietnamese: 'giảm giá', phonetic: 'đết-cuen-tô', emoji: '🏷️', example: 'Hay un 20% de descuento.', exampleVi: 'Giảm 20%.' },
  { id: 'nu18', spanish: 'gratis', vietnamese: 'miễn phí', phonetic: 'gra-tit', emoji: '🆓', example: 'La entrada es gratis.', exampleVi: 'Vé miễn phí.' },
  { id: 'nu19', spanish: 'primero', vietnamese: 'thứ nhất', phonetic: 'pri-mê-rô', emoji: '🥇', example: 'Soy el primero.', exampleVi: 'Tôi thứ nhất.' },
  { id: 'nu20', spanish: 'segundo', vietnamese: 'thứ hai', phonetic: 'xê-gun-đô', emoji: '🥈', example: 'El segundo piso.', exampleVi: 'Tầng 2.' },
  { id: 'nu21', spanish: 'tercero', vietnamese: 'thứ ba', phonetic: 'ter-xê-rô', emoji: '🥉', example: 'La tercera vez.', exampleVi: 'Lần thứ 3.' },
  { id: 'nu22', spanish: 'medio', vietnamese: 'một nửa', phonetic: 'mê-đi-ô', emoji: '½', example: 'Medio kilo.', exampleVi: 'Nửa ký.' },
  { id: 'nu23', spanish: 'doble', vietnamese: 'gấp đôi', phonetic: 'đô-blê', emoji: '✖️', example: 'El doble de tiempo.', exampleVi: 'Gấp đôi thời gian.' },
  { id: 'nu24', spanish: 'cuarto', vietnamese: 'một phần tư', phonetic: 'cuar-tô', emoji: '¼', example: 'Un cuarto de hora.', exampleVi: '15 phút.' },
  { id: 'nu25', spanish: 'propina', vietnamese: 'tiền boa', phonetic: 'prô-pi-na', emoji: '💰', example: '¿Dejamos propina?', exampleVi: 'Để tiền boa không?' },
  { id: 'nu26', spanish: 'factura', vietnamese: 'hóa đơn (mua hàng)', phonetic: 'phac-tu-ra', emoji: '📃', example: '¿Puede darme la factura?', exampleVi: 'Cho tôi hóa đơn.' },
  { id: 'nu27', spanish: 'efectivo', vietnamese: 'tiền mặt', phonetic: 'ê-phếc-ti-bô', emoji: '💵', example: 'Pago en efectivo.', exampleVi: 'Trả tiền mặt.' },
  { id: 'nu28', spanish: 'tarjeta', vietnamese: 'thẻ', phonetic: 'tar-hê-ta', emoji: '💳', example: 'Pago con tarjeta.', exampleVi: 'Trả bằng thẻ.' },
  { id: 'nu29', spanish: 'suficiente', vietnamese: 'đủ', phonetic: 'xu-phi-xi-en-tê', emoji: '✅', example: 'Es suficiente.', exampleVi: 'Đủ rồi.' },
  { id: 'nu30', spanish: 'demasiado', vietnamese: 'quá nhiều', phonetic: 'đê-ma-xi-a-đô', emoji: '📈', example: 'Es demasiado caro.', exampleVi: 'Đắt quá.' },
];

const health: FlashcardWord[] = [
  { id: 'he1', spanish: 'cabeza', vietnamese: 'đầu', phonetic: 'ca-bê-xa', emoji: '🗣️', example: 'Me duele la cabeza.', exampleVi: 'Tôi đau đầu.' },
  { id: 'he2', spanish: 'mano', vietnamese: 'tay', phonetic: 'ma-nô', emoji: '🤚', example: 'Dame la mano.', exampleVi: 'Đưa tay đây.' },
  { id: 'he3', spanish: 'corazón', vietnamese: 'trái tim', phonetic: 'cô-ra-xôn', emoji: '❤️', example: 'Mi corazón late fuerte.', exampleVi: 'Tim tôi đập mạnh.' },
  { id: 'he4', spanish: 'enfermo', vietnamese: 'ốm', phonetic: 'en-pher-mô', emoji: '🤒', example: 'Estoy enfermo.', exampleVi: 'Tôi ốm.' },
  { id: 'he5', spanish: 'medicina', vietnamese: 'thuốc', phonetic: 'mê-đi-xi-na', emoji: '💊', example: 'Necesito medicina.', exampleVi: 'Tôi cần thuốc.' },
  { id: 'he6', spanish: 'dolor', vietnamese: 'đau', phonetic: 'đô-lor', emoji: '😣', example: 'Tengo dolor de espalda.', exampleVi: 'Tôi đau lưng.' },
  { id: 'he7', spanish: 'ojo', vietnamese: 'mắt', phonetic: 'ô-hô', emoji: '👁️', example: 'Tengo ojos bonitos.', exampleVi: 'Mắt đẹp.' },
  { id: 'he8', spanish: 'oreja', vietnamese: 'tai', phonetic: 'ô-rê-ha', emoji: '👂', example: 'Me duele la oreja.', exampleVi: 'Tôi đau tai.' },
  { id: 'he9', spanish: 'nariz', vietnamese: 'mũi', phonetic: 'na-rít', emoji: '👃', example: 'Tengo la nariz tapada.', exampleVi: 'Tôi bị nghẹt mũi.' },
  { id: 'he10', spanish: 'boca', vietnamese: 'miệng', phonetic: 'bô-ca', emoji: '👄', example: 'Abre la boca.', exampleVi: 'Mở miệng.' },
  { id: 'he11', spanish: 'diente', vietnamese: 'răng', phonetic: 'đi-en-tê', emoji: '🦷', example: 'Me duele un diente.', exampleVi: 'Tôi đau răng.' },
  { id: 'he12', spanish: 'garganta', vietnamese: 'cổ họng', phonetic: 'gar-gan-ta', emoji: '🤧', example: 'Me duele la garganta.', exampleVi: 'Tôi đau họng.' },
  { id: 'he13', spanish: 'estómago', vietnamese: 'dạ dày', phonetic: 'ét-tô-ma-gô', emoji: '🤢', example: 'Me duele el estómago.', exampleVi: 'Tôi đau bụng.' },
  { id: 'he14', spanish: 'espalda', vietnamese: 'lưng', phonetic: 'ét-pal-đa', emoji: '🔙', example: 'Me duele la espalda.', exampleVi: 'Tôi đau lưng.' },
  { id: 'he15', spanish: 'pierna', vietnamese: 'chân (đùi)', phonetic: 'pi-er-na', emoji: '🦵', example: 'Me duele la pierna.', exampleVi: 'Tôi đau chân.' },
  { id: 'he16', spanish: 'pie', vietnamese: 'bàn chân', phonetic: 'pi-ê', emoji: '🦶', example: 'Me duele el pie.', exampleVi: 'Tôi đau bàn chân.' },
  { id: 'he17', spanish: 'brazo', vietnamese: 'cánh tay', phonetic: 'bra-xô', emoji: '💪', example: 'Me duele el brazo.', exampleVi: 'Tôi đau tay.' },
  { id: 'he18', spanish: 'rodilla', vietnamese: 'đầu gối', phonetic: 'rô-đi-gia', emoji: '🦿', example: 'Me duele la rodilla.', exampleVi: 'Tôi đau đầu gối.' },
  { id: 'he19', spanish: 'fiebre', vietnamese: 'sốt', phonetic: 'phi-ê-brê', emoji: '🤒', example: 'Tengo fiebre.', exampleVi: 'Tôi bị sốt.' },
  { id: 'he20', spanish: 'tos', vietnamese: 'ho', phonetic: 'tốt', emoji: '😷', example: 'Tengo tos.', exampleVi: 'Tôi bị ho.' },
  { id: 'he21', spanish: 'gripe', vietnamese: 'cúm', phonetic: 'gri-pê', emoji: '🤧', example: 'Tengo gripe.', exampleVi: 'Tôi bị cúm.' },
  { id: 'he22', spanish: 'alergia', vietnamese: 'dị ứng', phonetic: 'a-ler-hi-a', emoji: '🤧', example: 'Tengo alergia al polen.', exampleVi: 'Tôi dị ứng phấn hoa.' },
  { id: 'he23', spanish: 'hospital', vietnamese: 'bệnh viện', phonetic: 'ốt-pi-tal', emoji: '🏥', example: 'Voy al hospital.', exampleVi: 'Tôi đi bệnh viện.' },
  { id: 'he24', spanish: 'farmacia', vietnamese: 'hiệu thuốc', phonetic: 'phar-ma-xi-a', emoji: '💊', example: '¿Dónde hay una farmacia?', exampleVi: 'Hiệu thuốc ở đâu?' },
  { id: 'he25', spanish: 'receta', vietnamese: 'đơn thuốc', phonetic: 'rê-xê-ta', emoji: '📋', example: 'Necesito receta.', exampleVi: 'Tôi cần đơn thuốc.' },
  { id: 'he26', spanish: 'pastilla', vietnamese: 'viên thuốc', phonetic: 'pat-ti-gia', emoji: '💊', example: 'Toma una pastilla.', exampleVi: 'Uống một viên thuốc.' },
  { id: 'he27', spanish: 'jarabe', vietnamese: 'siro', phonetic: 'ha-ra-bê', emoji: '🍯', example: 'Jarabe para la tos.', exampleVi: 'Siro ho.' },
  { id: 'he28', spanish: 'sangre', vietnamese: 'máu', phonetic: 'xan-grê', emoji: '🩸', example: 'Análisis de sangre.', exampleVi: 'Xét nghiệm máu.' },
  { id: 'he29', spanish: 'pelo', vietnamese: 'tóc', phonetic: 'pê-lô', emoji: '💇', example: 'Tengo el pelo largo.', exampleVi: 'Tóc tôi dài.' },
  { id: 'he30', spanish: 'piel', vietnamese: 'da', phonetic: 'pi-el', emoji: '🧴', example: 'Tengo la piel seca.', exampleVi: 'Da tôi khô.' },
];

const nature: FlashcardWord[] = [
  { id: 'na1', spanish: 'sol', vietnamese: 'mặt trời', phonetic: 'xol', emoji: '☀️', example: 'Hace sol hoy.', exampleVi: 'Hôm nay có nắng.' },
  { id: 'na2', spanish: 'lluvia', vietnamese: 'mưa', phonetic: 'giu-bia', emoji: '🌧️', example: 'Hay lluvia.', exampleVi: 'Trời mưa.' },
  { id: 'na3', spanish: 'árbol', vietnamese: 'cây', phonetic: 'ar-bol', emoji: '🌳', example: 'El árbol es alto.', exampleVi: 'Cây cao.' },
  { id: 'na4', spanish: 'playa', vietnamese: 'bãi biển', phonetic: 'pla-gia', emoji: '🏖️', example: 'Vamos a la playa.', exampleVi: 'Đi biển thôi.' },
  { id: 'na5', spanish: 'montaña', vietnamese: 'núi', phonetic: 'mon-ta-nha', emoji: '⛰️', example: 'La montaña es hermosa.', exampleVi: 'Núi đẹp.' },
  { id: 'na6', spanish: 'río', vietnamese: 'sông', phonetic: 'ri-ô', emoji: '🏞️', example: 'El río es largo.', exampleVi: 'Sông dài.' },
  { id: 'na7', spanish: 'viento', vietnamese: 'gió', phonetic: 'bi-en-tô', emoji: '💨', example: 'Hace mucho viento.', exampleVi: 'Gió to.' },
  { id: 'na8', spanish: 'mar', vietnamese: 'biển', phonetic: 'mar', emoji: '🌊', example: 'El mar es azul.', exampleVi: 'Biển xanh.' },
  { id: 'na9', spanish: 'flor', vietnamese: 'hoa', phonetic: 'phlor', emoji: '🌸', example: 'Las flores son bonitas.', exampleVi: 'Hoa đẹp.' },
  { id: 'na10', spanish: 'cielo', vietnamese: 'bầu trời', phonetic: 'xi-ê-lô', emoji: '🌤️', example: 'El cielo es azul.', exampleVi: 'Bầu trời xanh.' },
  { id: 'na11', spanish: 'nieve', vietnamese: 'tuyết', phonetic: 'ni-ê-bê', emoji: '❄️', example: 'Hay nieve en la montaña.', exampleVi: 'Có tuyết trên núi.' },
  { id: 'na12', spanish: 'nube', vietnamese: 'mây', phonetic: 'nu-bê', emoji: '☁️', example: 'Hay muchas nubes.', exampleVi: 'Nhiều mây.' },
  { id: 'na13', spanish: 'estrella', vietnamese: 'ngôi sao', phonetic: 'ét-trê-gia', emoji: '⭐', example: 'Las estrellas brillan.', exampleVi: 'Sao sáng.' },
  { id: 'na14', spanish: 'luna', vietnamese: 'mặt trăng', phonetic: 'lu-na', emoji: '🌙', example: 'La luna es bonita.', exampleVi: 'Mặt trăng đẹp.' },
  { id: 'na15', spanish: 'lago', vietnamese: 'hồ', phonetic: 'la-gô', emoji: '🏞️', example: 'El lago es tranquilo.', exampleVi: 'Hồ yên tĩnh.' },
  { id: 'na16', spanish: 'bosque', vietnamese: 'rừng', phonetic: 'bốt-kê', emoji: '🌲', example: 'El bosque es grande.', exampleVi: 'Rừng rộng.' },
  { id: 'na17', spanish: 'campo', vietnamese: 'đồng quê', phonetic: 'cam-pô', emoji: '🌾', example: 'Me gusta el campo.', exampleVi: 'Tôi thích đồng quê.' },
  { id: 'na18', spanish: 'isla', vietnamese: 'đảo', phonetic: 'ít-la', emoji: '🏝️', example: 'La isla es pequeña.', exampleVi: 'Đảo nhỏ.' },
  { id: 'na19', spanish: 'desierto', vietnamese: 'sa mạc', phonetic: 'đê-xi-er-tô', emoji: '🏜️', example: 'El desierto es caliente.', exampleVi: 'Sa mạc nóng.' },
  { id: 'na20', spanish: 'cascada', vietnamese: 'thác nước', phonetic: 'cát-ca-đa', emoji: '🌊', example: 'La cascada es hermosa.', exampleVi: 'Thác nước đẹp.' },
  { id: 'na21', spanish: 'tierra', vietnamese: 'đất', phonetic: 'ti-ê-rra', emoji: '🌍', example: 'La Tierra es redonda.', exampleVi: 'Trái Đất tròn.' },
  { id: 'na22', spanish: 'hierba', vietnamese: 'cỏ', phonetic: 'i-er-ba', emoji: '🌿', example: 'La hierba es verde.', exampleVi: 'Cỏ xanh.' },
  { id: 'na23', spanish: 'animal', vietnamese: 'động vật', phonetic: 'a-ni-mal', emoji: '🐾', example: 'Me gustan los animales.', exampleVi: 'Tôi thích động vật.' },
  { id: 'na24', spanish: 'perro', vietnamese: 'chó', phonetic: 'pe-rrô', emoji: '🐕', example: 'Tengo un perro.', exampleVi: 'Tôi có chó.' },
  { id: 'na25', spanish: 'gato', vietnamese: 'mèo', phonetic: 'ga-tô', emoji: '🐈', example: 'El gato duerme.', exampleVi: 'Mèo ngủ.' },
  { id: 'na26', spanish: 'pájaro', vietnamese: 'chim', phonetic: 'pa-ha-rô', emoji: '🐦', example: 'El pájaro canta.', exampleVi: 'Chim hót.' },
  { id: 'na27', spanish: 'pez', vietnamese: 'cá (sống)', phonetic: 'pết', emoji: '🐠', example: 'El pez nada.', exampleVi: 'Cá bơi.' },
  { id: 'na28', spanish: 'mariposa', vietnamese: 'bướm', phonetic: 'ma-ri-pô-xa', emoji: '🦋', example: 'La mariposa es bonita.', exampleVi: 'Bướm đẹp.' },
  { id: 'na29', spanish: 'tormenta', vietnamese: 'bão', phonetic: 'tor-men-ta', emoji: '⛈️', example: 'Hay tormenta.', exampleVi: 'Có bão.' },
  { id: 'na30', spanish: 'arcoíris', vietnamese: 'cầu vồng', phonetic: 'ar-cô-i-rit', emoji: '🌈', example: '¡Mira el arcoíris!', exampleVi: 'Nhìn cầu vồng!' },
];

export const FLASHCARD_CATEGORIES: FlashcardCategory[] = [
  { name: 'Đồ Vật', emoji: '🏠', color: 'hsl(37 90% 55%)', words: objects },
  { name: 'Động Từ', emoji: '🏃', color: 'hsl(5 78% 57%)', words: verbs },
  { name: 'Thời Gian', emoji: '📅', color: 'hsl(210 80% 55%)', words: time },
  { name: 'Con Người', emoji: '👥', color: 'hsl(280 60% 55%)', words: people },
  { name: 'Đồ Ăn', emoji: '🍕', color: 'hsl(15 90% 55%)', words: food },
  { name: 'Màu & Hình', emoji: '🎨', color: 'hsl(340 70% 55%)', words: colors },
  { name: 'Cảm Xúc', emoji: '😊', color: 'hsl(45 95% 50%)', words: feelings },
  { name: 'Số & Tiền', emoji: '💰', color: 'hsl(145 63% 42%)', words: numbers },
  { name: 'Sức Khỏe', emoji: '🏥', color: 'hsl(170 60% 45%)', words: health },
  { name: 'Thiên Nhiên', emoji: '🌳', color: 'hsl(120 50% 45%)', words: nature },
];

export function getAllFlashcardWords(): FlashcardWord[] {
  return FLASHCARD_CATEGORIES.flatMap(c => c.words);
}
